# ==============================================================================
# Merged Lakeflow Source: wiz
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import (
    Any,
    Iterator,
    List,
    Optional,
    Sequence,
)
import copy
import json
import time

from .wiz_client_mock import get_mock_wiz_client
from .wiz_schemas import BRONZE_SCHEMA, EVENT_CONFIGS, TABLES
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib import error, parse, request as urllib_request
import base64
import hashlib


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/wiz/wiz_client.py
    ########################################################

    class GraphQLClientError(RuntimeError):
        """Raised when OAuth or GraphQL requests fail."""


    @dataclass(slots=True)
    class WizGraphQLClient:
        """
        Production GraphQL client for the Wiz API.

        Handles OAuth2 client-credentials token fetch + auto-refresh,
        single GraphQL execute(), and full cursor-paginated paginate_connection().

        SOURCE: copied verbatim from WIZ_Collector notebook Step 2.
        """

        base_url:        str
        client_id:       str | None = None
        client_secret:   str | None = None
        audience:        str        = "wiz-api"
        timeout_seconds: int        = 60
        auth_enabled:    bool       = True
        access_token:    str | None = None
        _token_expiry:   float      = field(default=0.0, init=False, repr=False)

        def __post_init__(self) -> None:
            self.base_url = self.base_url.rstrip("/")
            if self.auth_enabled and not self.access_token:
                if not self.client_id or not self.client_secret:
                    raise GraphQLClientError(
                        "client_id and client_secret required when auth_enabled=True"
                    )

        @property
        def oauth_url(self) -> str:
            return f"{self.base_url}/oauth/token"

        @property
        def graphql_url(self) -> str:
            return f"{self.base_url}/graphql"

        def authenticate(self) -> str | None:
            """Fetch and cache bearer token; auto-refreshes before expiry."""
            if not self.auth_enabled:
                return None
            if self.access_token and time.time() < self._token_expiry - 60:
                return self.access_token
            payload = parse.urlencode({
                "grant_type":    "client_credentials",
                "audience":      self.audience,
                "client_id":     self.client_id,
                "client_secret": self.client_secret,
            }).encode("utf-8")
            resp = self._send_request(
                url=self.oauth_url, method="POST", body=payload,
                headers={"Content-Type": "application/x-www-form-urlencoded"},
            )
            token = resp.get("access_token")
            if not isinstance(token, str) or not token:
                raise GraphQLClientError("OAuth response missing access_token")
            self.access_token  = token
            self._token_expiry = time.time() + int(resp.get("expires_in", 3300))
            return token

        def execute(
            self,
            query: str,
            variables: dict[str, Any] | None = None,
        ) -> dict[str, Any]:
            """Execute one GraphQL operation and return the data dict."""
            token   = self.authenticate()
            headers = {"Content-Type": "application/json"}
            if token:
                headers["Authorization"] = f"Bearer {token}"
            resp = self._send_request(
                url=self.graphql_url, method="POST",
                body=json.dumps({"query": query, "variables": variables or {}}).encode(),
                headers=headers,
            )
            errors = resp.get("errors")
            if isinstance(errors, list) and errors:
                raise GraphQLClientError(f"GraphQL errors: {json.dumps(errors)}")
            data = resp.get("data")
            if not isinstance(data, dict):
                raise GraphQLClientError("GraphQL response missing 'data' object")
            return data

        def paginate_connection(
            self,
            *,
            query: str,
            connection_field: str,
            variables: dict[str, Any] | None = None,
            page_size: int = 500,
            max_pages: int | None = None,
            on_page: Any = None,
        ) -> list[dict[str, Any]]:
            """
            Collect all nodes from a Wiz-style cursor-paginated connection.

            on_page: optional callback(batch, page_num, end_cursor)
            """
            vars_: dict[str, Any] = dict(variables or {})
            vars_["first"] = page_size
            if "after" not in vars_:
                vars_["after"] = None

            nodes: list[dict[str, Any]] = []
            page_count = 0

            while True:
                data       = self.execute(query=query, variables=vars_)
                connection = data.get(connection_field)
                if not isinstance(connection, dict):
                    raise GraphQLClientError(f"Missing connection field '{connection_field}'")

                batch      = [n for n in connection.get("nodes", []) if isinstance(n, dict)]
                nodes.extend(batch)

                page_info  = connection.get("pageInfo", {})
                has_next   = bool(page_info.get("hasNextPage"))
                end_cursor = page_info.get("endCursor")
                page_count += 1

                if callable(on_page):
                    on_page(batch, page_count, end_cursor)

                if not has_next:
                    break
                if max_pages is not None and page_count >= max_pages:
                    break
                if not isinstance(end_cursor, str) or not end_cursor:
                    raise GraphQLClientError("hasNextPage=true but endCursor is empty")
                vars_["after"] = end_cursor

            return nodes

        def _send_request(
            self,
            *,
            url: str,
            method: str,
            body: bytes,
            headers: dict[str, str],
        ) -> dict[str, Any]:
            req = urllib_request.Request(url=url, data=body, method=method, headers=headers)
            try:
                with urllib_request.urlopen(req, timeout=self.timeout_seconds) as resp:
                    raw = resp.read().decode("utf-8")
            except error.HTTPError as exc:
                raise GraphQLClientError(
                    f"HTTP {exc.code} from {url}: {exc.read().decode('utf-8', errors='replace')}"
                ) from exc
            except error.URLError as exc:
                raise GraphQLClientError(f"Request failed for {url}: {exc.reason}") from exc
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise GraphQLClientError(f"Non-JSON from {url}: {raw[:200]}") from exc
            if not isinstance(parsed, dict):
                raise GraphQLClientError(f"Response from {url} was not a JSON object")
            return parsed


    def get_wiz_client(options: dict) -> WizGraphQLClient:
        """
        Factory function — mirrors get_api() pattern from the example connector.

        Called by WizLakeflowConnect.__init__ when options["use_mock"] is absent
        or False. Reads credentials from the options dict which comes from
        spec.yaml → Databricks secret scope.

        options dict expected keys (same format as your existing collector secret):
            base_url       : "https://api.us20.app.wiz.io"
            client_id      : "..."
            client_secret  : "..."
            audience       : "wiz-api"           (optional, default shown)
            auth_enabled   : true                (optional, default true)
        """
        return WizGraphQLClient(
            base_url      = options["base_url"],
            client_id     = options.get("client_id"),
            client_secret = options.get("client_secret"),
            audience      = options.get("audience", "wiz-api"),
            auth_enabled  = options.get("auth_enabled", True),
        )


    ########################################################
    # src/databricks/labs/community_connector/sources/wiz/wiz_client_mock.py
    ########################################################

    class GraphQLClientError(RuntimeError):
        """Raised when OAuth or GraphQL requests fail."""


    @dataclass(slots=True)
    class WizGraphQLClientMock:
        """Production GraphQL client for the Wiz API."""

        base_url:        str
        client_id:       str | None = None
        client_secret:   str | None = None
        audience:        str        = "wiz-api"
        timeout_seconds: int        = 60
        auth_enabled:    bool       = True
        access_token:    str | None = None
        _token_expiry:   float      = field(default=0.0, init=False, repr=False)

        def __post_init__(self) -> None:
            self.base_url = self.base_url.rstrip("/")
            if self.auth_enabled and not self.access_token:
                if not self.client_id or not self.client_secret:
                    raise GraphQLClientError("client_id and client_secret required when auth_enabled=True")

        @property
        def oauth_url(self)    -> str: return f"{self.base_url}/oauth/token"
        @property
        def graphql_url(self)  -> str: return f"{self.base_url}/graphql"

        def authenticate(self) -> str | None:
            """Fetch and cache bearer token; auto-refreshes before expiry."""
            if not self.auth_enabled:
                return None
            if self.access_token and time.time() < self._token_expiry - 60:
                return self.access_token
            payload = parse.urlencode({
                "grant_type": "client_credentials", "audience": self.audience,
                "client_id": self.client_id, "client_secret": self.client_secret,
            }).encode("utf-8")
            resp = self._send_request(url=self.oauth_url, method="POST", body=payload,
                                      headers={"Content-Type": "application/x-www-form-urlencoded"})
            token = resp.get("access_token")
            if not isinstance(token, str) or not token:
                raise GraphQLClientError("OAuth response missing access_token")
            self.access_token = token
            self._token_expiry = time.time() + int(resp.get("expires_in", 3300))
            return token

        def execute(self, query: str, variables: dict[str, Any] | None = None) -> dict[str, Any]:
            """Execute one GraphQL operation and return the data dict."""
            token   = self.authenticate()
            headers = {"Content-Type": "application/json"}
            if token:
                headers["Authorization"] = f"Bearer {token}"
            resp   = self._send_request(url=self.graphql_url, method="POST",
                                         body=json.dumps({"query": query, "variables": variables or {}}).encode(),
                                         headers=headers)
            errors = resp.get("errors")
            if isinstance(errors, list) and errors:
                raise GraphQLClientError(f"GraphQL errors: {json.dumps(errors)}")
            data = resp.get("data")
            if not isinstance(data, dict):
                raise GraphQLClientError("GraphQL response missing 'data' object")
            return data

        def paginate_connection(self, *, query: str, connection_field: str,
                                 variables: dict[str, Any] | None = None,
                                 page_size: int = 500, max_pages: int | None = None,
                                 on_page: Any = None) -> list[dict[str, Any]]:
            """
            Collect all nodes from a Wiz-style cursor-paginated connection.

            on_page: optional callback(batch, page_num, end_cursor) — used by
                     detection collector to save cursor after every page.
            """
            vars_: dict[str, Any] = dict(variables or {})
            vars_["first"] = page_size
            if "after" not in vars_:
                vars_["after"] = None

            nodes: list[dict[str, Any]] = []
            page_count = 0

            while True:
                data       = self.execute(query=query, variables=vars_)
                connection = data.get(connection_field)
                if not isinstance(connection, dict):
                    raise GraphQLClientError(f"Missing connection field '{connection_field}'")

                batch = [n for n in connection.get("nodes", []) if isinstance(n, dict)]
                nodes.extend(batch)

                page_info  = connection.get("pageInfo", {})
                has_next   = bool(page_info.get("hasNextPage"))
                end_cursor = page_info.get("endCursor")
                page_count += 1

                if callable(on_page):
                    on_page(batch, page_count, end_cursor)

                if not has_next:
                    break
                if max_pages is not None and page_count >= max_pages:
                    print(f"    ⚠️  max_pages={max_pages} reached")
                    break
                if not isinstance(end_cursor, str) or not end_cursor:
                    raise GraphQLClientError("hasNextPage=true but endCursor is empty")
                vars_["after"] = end_cursor

            return nodes

        def _send_request(self, *, url: str, method: str, body: bytes,
                           headers: dict[str, str]) -> dict[str, Any]:
            req = urllib_request.Request(url=url, data=body, method=method, headers=headers)
            try:
                with urllib_request.urlopen(req, timeout=self.timeout_seconds) as resp:
                    raw = resp.read().decode("utf-8")
            except error.HTTPError as exc:
                raise GraphQLClientError(f"HTTP {exc.code} from {url}: {exc.read().decode('utf-8', errors='replace')}") from exc
            except error.URLError as exc:
                raise GraphQLClientError(f"Request failed for {url}: {exc.reason}") from exc
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise GraphQLClientError(f"Non-JSON from {url}: {raw[:200]}") from exc
            if not isinstance(parsed, dict):
                raise GraphQLClientError(f"Response from {url} was not a JSON object")
            return parsed


    def get_mock_wiz_client(options: dict) -> WizGraphQLClientMock:
        """
        Factory function — mirrors get_api() pattern from the example connector.

        Called by WizLakeflowConnect.__init__ when options["use_mock"] is absent
        or False. Reads credentials from the options dict which comes from
        spec.yaml → Databricks secret scope.

        options dict expected keys (same format as your existing collector secret):
            base_url       : "https://api.us20.app.wiz.io"
            client_id      : "..."
            client_secret  : "..."
            audience       : "wiz-api"           (optional, default shown)
            auth_enabled   : true                (optional, default true)
        """
        print("Options are:", options)
        # 🔥 handle JSON secret
        if "config_json" in options:
            config = json.loads(options["config_json"])
        else:
            config = options

        #config = options
        return WizGraphQLClientMock(
            base_url=config["base_url"],
            client_id=config.get("client_id"),
            client_secret=config.get("client_secret"),
            audience=config.get("audience", "wiz-api"),
            auth_enabled=config.get("auth_enabled", True)
        )


    ########################################################
    # src/databricks/labs/community_connector/sources/wiz/wiz_schemas.py
    ########################################################

    BRONZE_SCHEMA = StructType([
        StructField("lw_id", StringType(), True),
        StructField("time", TimestampType(), True),
        StructField("_raw_json", VariantType(), True), 
        StructField("collected_at", TimestampType(), True),
        StructField("event_type", StringType(), True),
        StructField("record_id", StringType(), True),
        StructField("_metadata", StringType(), True),
    ])

    # ── Tables exposed by this connector ─────────────────────────────────────────-
    TABLES = ["wiz_security_events_test"]

    # ── GraphQL queries ───────────────────────────────────────────────────────────

    ISSUES_QUERY = """
    query IssuesTable($filterBy: IssueFilters, $first: Int, $after: String, $orderBy: IssueOrder) {
      issues: issuesV2(filterBy: $filterBy, first: $first, after: $after, orderBy: $orderBy) {
        nodes {
          id
          sourceRule {
            __typename
            ... on Control {
              id name controlDescription: description resolutionRecommendation risks threats
              securitySubCategories { title id category { name id framework { id name } } }
            }
            ... on CloudEventRule {
              id name cloudEventRuleDescription: description sourceType type risks threats
            }
            ... on CloudConfigurationRule {
              id name cloudConfigurationRuleDescription: description remediationInstructions serviceType risks
              securitySubCategories { title id category { name id framework { id name } } }
            }
          }
          createdAt updatedAt dueAt type resolvedAt statusChangedAt status severity
          projects { id name slug businessUnit riskProfile { businessImpact } }
          threatDetectionDetails { eventOrigin }
          entitySnapshot {
            id type nativeType name status cloudPlatform cloudProviderURL providerId region
            resourceGroupExternalId subscriptionExternalId subscriptionName subscriptionTags
            tags createdAt externalId
          }
          serviceTickets { externalId name url }
          notes { createdAt updatedAt text user { name email } serviceAccount { name } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }
    """

    VULNS_QUERY = """
    query vulnerabilityFindings($first: Int, $after: String, $filterBy: VulnerabilityFindingFilters, $orderBy: VulnerabilityFindingOrder) {
      vulnerabilityFindings(first: $first, after: $after, filterBy: $filterBy, orderBy: $orderBy) {
        nodes {
          id portalUrl name CVEDescription fixDateDescription description CVSSSeverity
          hasExploit score exploitabilityScore impactScore hasCisaKevExploit vendorSeverity
          firstDetectedAt lastDetectedAt resolvedAt remediation locationPath detailedName
          version fixedVersion detectionMethod link status epssSeverity epssPercentile
          epssProbability validatedInRuntime
          layerMetadata { id details isBaseLayer }
          projects { name projectOwners { email } }
          relatedIssueAnalytics {
            criticalSeverityCount highSeverityCount mediumSeverityCount
            lowSeverityCount informationalSeverityCount
          }
          vulnerableAsset {
            ... on VulnerableAssetBase {
              id type name region providerUniqueId cloudProviderURL cloudPlatform status
              subscriptionExternalId subscriptionId subscriptionName tags
              hasLimitedInternetExposure hasWideInternetExposure isAccessibleFromVPN
              isAccessibleFromOtherVnets isAccessibleFromOtherSubscriptions scanSource
            }
            ... on VulnerableAssetVirtualMachine { operatingSystem ipAddresses }
            ... on VulnerableAssetContainerImage  { imageId }
            ... on VulnerableAssetServerless      { runtime }
            ... on VulnerableAssetContainer       { ImageExternalId VmExternalId ServerlessContainer PodNamespace PodName NodeName }
            ... on VulnerableAssetRepositoryBranch { repositoryId repositoryName repositoryExternalId }
          }
        }
        pageInfo { endCursor hasNextPage }
      }
    }
    """

    AUDIT_LOGS_QUERY = """
    query AuditLogTable($first: Int, $after: String, $filterBy: AuditLogEntryFilters) {
      auditLogEntries(first: $first, after: $after, filterBy: $filterBy) {
        nodes {
          id action requestId status timestamp actionParameters userAgent sourceIP
          serviceAccount { id name }
          user { id name }
        }
        pageInfo { hasNextPage endCursor }
      }
    }
    """

    DETECTIONS_QUERY = """
    query Detections($filterBy: DetectionFilters, $first: Int, $after: String, $orderBy: DetectionOrder, $includeTriggeringEvents: Boolean = true) {
      detections(filterBy: $filterBy, first: $first, after: $after, orderBy: $orderBy, enforceTimestampContinuity: true) {
        nodes {
          id
          issue { id url }
          ruleMatch { rule { id name sourceType securitySubCategories { title category { name framework { name } } } } }
          description severity createdAt startedAt endedAt
          cloudAccounts { cloudProvider externalId name linkedProjects { id name } }
          cloudOrganizations { cloudProvider externalId name }
          actors { id externalId name type nativeType actingAs { id externalId name type nativeType } }
          primaryActor { id }
          resources {
            id externalId name type nativeType region
            cloudAccount { cloudProvider externalId name }
            kubernetesNamespace { id providerUniqueId name }
            kubernetesCluster { id providerUniqueId name }
          }
          primaryResource { id }
          triggeringEvents(first: 10) @include(if: $includeTriggeringEvents) {
            nodes {
              ... on CloudEvent {
                id origin name description cloudProviderUrl cloudPlatform timestamp source category status
                actor { id actingAs { id } }
                actorIP
                actorIPMeta {
                  country autonomousSystemNumber autonomousSystemOrganization reputation
                  reputationDescription reputationSource relatedAttackGroupNames
                  customIPRanges { id name isInternal ipRanges }
                }
                resources { id }
                extraDetails {
                  ... on CloudEventRuntimeDetails {
                    processTree { command path hash size executionTime runtimeProgramId userId userName
                      container { id externalId name image { id externalId } }
                    }
                  }
                }
              }
            }
          }
        }
        pageInfo { hasNextPage endCursor }
      }
    }
    """

    # ── EVENT_CONFIGS ─────────────────────────────────────────────────────────────
    # Copied verbatim from WIZ_Collector notebook Step 4. Zero changes.
    # source.py reads from this dict — no hardcoded constants in collector logic.

    EVENT_CONFIGS: dict = {

        "issue": {
            "query":            ISSUES_QUERY,
            "connection_field": "issues",
            "page_size":        500,
            "filter_variables": {
                "severity": ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"],
                "project":  None,
            },
            "order_by": {"field": "CREATED_AT", "direction": "ASC"},
            "incremental": {
                "overlap_hours": 1,
            },
        },

        "vulnerability_finding": {
            "query":            VULNS_QUERY,
            "connection_field": "vulnerabilityFindings",
            "page_size":        500,
            "filter_variables": {
                "status":               ["OPEN", "IN_PROGRESS", "REJECTED", "RESOLVED"],
                "assetType":            ["SERVERLESS", "CONTAINER_IMAGE", "VIRTUAL_MACHINE",
                                         "CONTAINER", "REPOSITORY_BRANCH", "ENDPOINT"],
                "vendorSeverity":       ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"],
                "projectId":            None,
                "relatedIssueSeverity": None,
            },
            "incremental": {
                "overlap_hours": 1,
            },
        },

        "audit_log": {
            "query":            AUDIT_LOGS_QUERY,
            "connection_field": "auditLogEntries",
            "page_size":        500,
            "filter_variables": {},
            "incremental": {
                "historical_days": 10,
            },
        },

        "detection": {
            "query":            DETECTIONS_QUERY,
            "connection_field": "detections",
            "page_size":        50,
            "filter_variables": {
                "severity":  {"equals": ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"]},
                "projectId": None,
            },
            "order_by":                  {"field": "CREATED_AT", "direction": "ASC"},
            "include_triggering_events": True,
            "incremental": {
                "historical_days": 3,
            },
        },
    }


    def get_schema(table_name: str) -> StructType:
        """
        Minimal schema for Wiz connector.
        Matches what we emit in fetch functions.
        """

        return BRONZE_SCHEMA


    ########################################################
    # src/databricks/labs/community_connector/sources/wiz/wiz.py
    ########################################################

    class WizLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the simulated Example source."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            # ── Client selection: real or mock ────────────────────────────────────
            # options["use_mock"] = "true"  → WizMockClient (no credentials needed)
            # options["use_mock"] absent    → WizGraphQLClient (real Wiz API)
            #
            # In production (spec.yaml): use_mock is absent.
            # In local dev / unit tests:  set options["use_mock"] = "true"
            # In the Databricks job UI:   add use_mock = "true" as a task param
            #   to point the entire pipeline at mock data.
            use_mock = options.get("use_mock", "false").lower() == "true"
            #self._client = get_mock_wiz_client(options)


            if use_mock:
                self._client = get_mock_wiz_client(options)
                print("[WizLakeflowConnect] Using MOCK client — no real API calls")
            else:
                # Credentials come from the Databricks secret referenced in spec.yaml.
                # The framework loads the secret JSON and passes it as options.
                # Same JSON format as your existing WIZ_Collector secret:
                #   {"base_url": "...", "client_id": "...", "client_secret": "..."}
                self._client = get_wiz_client(options)
                print(f"[WizLakeflowConnect] Using REAL client → {options.get('base_url')}")

            # ── Config ────────────────────────────────────────────────────────────
            self._portal_url = options.get("portal_base_url", "https://app.wiz.io")
            self._configs    = copy.deepcopy(EVENT_CONFIGS)

            # Inject project_id if provided (mirrors your Step 4 widget injection)
            project_id = options.get("project_id")
            if project_id:
                self._configs["issue"]["filter_variables"]["project"]               = [project_id]
                self._configs["vulnerability_finding"]["filter_variables"]["projectId"] = project_id
                self._configs["detection"]["filter_variables"]["projectId"]         = project_id
                print(f"[WizLakeflowConnect] Scoped to project: {project_id}")

        def list_tables(self) -> list[str]:
            """
            Return the list of tables this connector exposes.
            Equivalent to example's list_tables() — but static (no API call needed).
            """
            return TABLES

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            """
            Return the Spark schema for table_name.
            All 4 Wiz tables share the same bronze schema.
            Silver/gold schemas live in your preset YAML — unchanged.
            """
            self._validate_table(table_name)
            return BRONZE_SCHEMA

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            """
            Return ingestion metadata for table_name.

            ingestion_type options:
                "cdc"          → cursor-based incremental (issues, vulns, audit_log)
                "append_only"  → cursor-based append, never updates (detection)
                "snapshot"     → full reload every run (not used for Wiz)

            cursor_field is the field name we track for incremental sync.
            The framework uses this in its generic offset validation tests.
            """
            self._validate_table(table_name)
            return {
                "ingestion_type": "cdc",
                "cursor_field": "collected_at",  # or "event_time"
                "description": "Unified Wiz events stream",
            }

        def read_table(
            self,
            table_name: str,
            start_offset: dict | None,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """
            Fetch records for table_name starting from start_offset.

            This is called by the framework on each scheduled pipeline run.
            Returns: (iterator_of_bronze_rows, end_offset)

            start_offset=None → first run → initial/full-load behaviour.
            The end_offset is saved by the framework and passed back as
            start_offset on the next run.

            ROUTING (mirrors example's read_table dispatcher):
                issue               → _read_issues()
                vulnerability_finding → _read_vulns()
                audit_log           → _read_audit_logs()
                detection           → _read_detections()  (cursor-based)
            """
            self._validate_table(table_name)
            now = datetime.now(timezone.utc)

            if table_name == "wiz_security_events_test":
                return self._read_all_events(start_offset, now)
            else:
                raise ValueError(f"Unsupported table: {table_name}")

        def _read_all_events(self, start_offset, now):
            # ── STEP 1 — split offsets ─────────────────────────────────────────────
            issue_offset = start_offset.get("issue") if start_offset else None
            vuln_offset = start_offset.get("vulnerability_finding") if start_offset else None
            audit_offset = start_offset.get("audit_log") if start_offset else None
            detection_offset = start_offset.get("detection") if start_offset else None

            # ── STEP 2 — call individual readers ───────────────────────────────────
            issue_rows, issue_end = self._read_issues(issue_offset, now)
            vuln_rows, vuln_end = self._read_vulns(vuln_offset, now)
            audit_rows, audit_end = self._read_audit_logs(audit_offset, now)
            detection_rows, detection_end = self._read_detections(detection_offset, now)

            # ── STEP 3 — merge rows using generator (memory-safe) ──────────────────
            def _chain(*iterators):
                for it in iterators:
                    if it is not None:
                        yield from it

            rows = _chain(issue_rows, vuln_rows, audit_rows, detection_rows)

            # ── STEP 4 — merge offsets ─────────────────────────────────────────────
            end_offset = {
                "issue": issue_end,
                "vulnerability_finding": vuln_end,
                "audit_log": audit_end,
                "detection": detection_end,
            }

            return rows, end_offset

        def _read_issues(
            self,
            start_offset: dict | None,
            now: datetime,
        ) -> tuple[Iterator[dict], dict]:
            """
            Offset shape:
                None                           → initial
                {"cursor": "...", 
                "full_sync": true}            → full_sync  (2-pass: active + RESOLVED)
                {"cursor": "...",
                "re_assessed": true}          → re_assessed
                {"cursor": "..."}              → incremental

            full_sync can be triggered two ways:
                1. Reset the offset to None externally (databricks pipelines reset)
                — this triggers initial, which is equivalent to full_sync pass 1
                2. Set full_sync = "true" in spec.yaml table options
                — preserves the existing cursor, runs both passes, then clears the flag
            """
            cfg       = self._configs["issue"]
            fv        = cfg["filter_variables"]
            # Read from table_options in spec.yaml — false by default
            full_sync = self.options.get("full_sync", "false").lower() == "true"

            def _paginate(filterBy: dict) -> list[dict]:
                return self._client.paginate_connection(
                    query=cfg["query"],
                    connection_field=cfg["connection_field"],
                    variables={"filterBy": filterBy, "orderBy": cfg["order_by"]},
                    page_size=cfg["page_size"],
                )

            nodes: list[dict] = []

            # ── initial ───────────────────────────────────────────────────────────────
            if start_offset is None or not start_offset.get("cursor"):
                filterBy = {"status": ["OPEN", "IN_PROGRESS"], "severity": fv["severity"]}
                if fv.get("project"):
                    filterBy["project"] = fv["project"]
                nodes.extend(_paginate(filterBy))
                end_offset = {"cursor": self._fmt(now)}

            # ── full_sync — checked before incremental so the flag always wins ────────
            elif full_sync:
                print("  [issue] full_sync — pass 1: OPEN, IN_PROGRESS, REJECTED")
                fby_p1 = {"status": ["OPEN", "IN_PROGRESS", "REJECTED"], "severity": fv["severity"]}
                if fv.get("project"):
                    fby_p1["project"] = fv["project"]
                pass1 = _paginate(fby_p1)
                nodes.extend(pass1)
                print(f"  [issue] full_sync pass 1 — {len(pass1)} records")

                # Pass 2: RESOLVED since last full_sync (falls back to 7d if no prior full_sync)
                last_full = (
                    start_offset.get("full_sync_cursor")
                    or self._fmt(now - timedelta(days=7))
                )
                print(f"  [issue] full_sync — pass 2: RESOLVED  resolvedAt: {last_full} → {self._fmt(now)}")
                fby_p2 = {
                    "status":     ["RESOLVED"],
                    "severity":   fv["severity"],
                    "resolvedAt": {"after": last_full, "before": self._fmt(now)},
                }
                if fv.get("project"):
                    fby_p2["project"] = fv["project"]
                pass2 = _paginate(fby_p2)
                nodes.extend(pass2)
                print(f"  [issue] full_sync pass 2 — {len(pass2)} RESOLVED")

                # Advance both cursors; consumer must set full_sync=false after this run
                end_offset = {
                    "cursor":           self._fmt(now),
                    "full_sync_cursor": self._fmt(now),
                }

            # ── re_assessed ───────────────────────────────────────────────────────────
            elif start_offset.get("re_assessed"):
                after     = start_offset.get("cursor", self._fmt(now - timedelta(hours=1)))
                before    = self._fmt(now)
                after_dt  = self._parse_ts(after)
                before_dt = self._parse_ts(before)

                fby_p1 = {"status": ["OPEN", "IN_PROGRESS", "REJECTED"], "severity": fv["severity"]}
                if fv.get("project"):
                    fby_p1["project"] = fv["project"]
                for issue in _paginate(fby_p1):
                    updated = issue.get("updatedAt", "")
                    try:
                        if updated and after_dt < self._parse_ts(updated) < before_dt:
                            nodes.append(issue)
                    except ValueError:
                        pass

                fby_p2 = {
                    "status":          ["RESOLVED"],
                    "severity":        fv["severity"],
                    "statusChangedAt": {"after": after, "before": before},
                }
                if fv.get("project"):
                    fby_p2["project"] = fv["project"]
                nodes.extend(_paginate(fby_p2))

                end_offset = {
                    "cursor":           self._fmt(now),
                    "full_sync_cursor": start_offset.get("full_sync_cursor"),
                    "re_assessed":      False,
                }

            # ── incremental ───────────────────────────────────────────────────────────
            else:
                after  = start_offset["cursor"]
                before = self._fmt(now)
                filterBy = {
                    "status":          ["OPEN", "IN_PROGRESS", "REJECTED", "RESOLVED"],
                    "severity":        fv["severity"],
                    "statusChangedAt": {"after": after, "before": before},
                }
                if fv.get("project"):
                    filterBy["project"] = fv["project"]
                nodes.extend(_paginate(filterBy))
                end_offset = {
                    "cursor":           self._fmt(now),
                    "full_sync_cursor": start_offset.get("full_sync_cursor"),
                }

            for n in nodes:
                n["sourceURL"]  = f"{self._portal_url}/issues#~(issue~'{n.get('id', '')}')"
                n["event_type"] = "issue"

            return iter(self._to_bronze(nodes, now)), end_offset

        # ─────────────────────────────────────────────────────────────────────────

        def _read_vulns(
            self,
            start_offset: dict | None,
            now: datetime,
        ) -> tuple[Iterator[dict], dict]:
            """
            REPLACES: collect_vulns() from notebook Step 9.

            Offset shape:
                None                          → initial (all statuses, no time filter)
                {"cursor": "<ISO timestamp>"} → incremental (statusUpdatedAt + overlap)
            """
            cfg = self._configs["vulnerability_finding"]
            fv  = cfg["filter_variables"]
            inc = cfg["incremental"]
            full_sync = self.options.get("full_sync", "false").lower() == "true"

            def _build_filter(extra: dict | None = None) -> dict:
                f: dict = {
                    "status":         fv["status"],
                    "assetType":      fv["assetType"],
                    "vendorSeverity": fv["vendorSeverity"],
                }
                if fv.get("projectId"):            f["projectId"]            = fv["projectId"]
                if fv.get("relatedIssueSeverity"): f["relatedIssueSeverity"] = fv["relatedIssueSeverity"]
                if extra:                          f.update(extra)
                return f

            order = {"field": "FIRST_DETECTED_AT", "direction": "ASC"}

            # ── initial ───────────────────────────────────────────────
            if start_offset is None or not start_offset.get("cursor") or full_sync:
                nodes = self._client.paginate_connection(
                    query=cfg["query"], connection_field=cfg["connection_field"],
                    variables={"filterBy": _build_filter(), "orderBy": order},
                    page_size=cfg["page_size"],
                )
                end_offset = {"cursor": self._fmt(now)}

            # ── incremental ───────────────────────────────────────────────────────
            else:
                overlap   = inc["overlap_hours"]
                last_dt   = self._parse_ts(start_offset["cursor"])
                after     = self._fmt(last_dt - timedelta(hours=overlap))
                before    = self._fmt(now)
                nodes = self._client.paginate_connection(
                    query=cfg["query"], connection_field=cfg["connection_field"],
                    variables={
                        "filterBy": _build_filter({"statusUpdatedAt": {"after": after, "before": before}}),
                        "orderBy":  order,
                    },
                    page_size=cfg["page_size"],
                )
                end_offset = {
                    "cursor":          self._fmt(now)
                }

            for n in nodes:
                n["event_type"] = "vulnerability_finding"

            return iter(self._to_bronze(nodes, now)), end_offset

        # ─────────────────────────────────────────────────────────────────────────

        def _read_audit_logs(
            self,
            start_offset: dict | None,
            now: datetime,
        ) -> tuple[Iterator[dict], dict]:
            """
            REPLACES: collect_audit_logs() from notebook Step 10.

            Offset shape:
                None                          → initial (now - historical_days → now)
                {"cursor": "<ISO timestamp>"} → incremental (last_timestamp → now)
            """
            cfg = self._configs["audit_log"]
            inc = cfg["incremental"]

            if start_offset is None or not start_offset.get("cursor"):
                after = self._fmt(now - timedelta(days=inc["historical_days"]))
            else:
                after = start_offset["cursor"]

            filterBy = {
                **cfg["filter_variables"],
                "timestamp": {"after": after, "before": self._fmt(now)},
            }

            nodes = self._client.paginate_connection(
                query=cfg["query"], connection_field=cfg["connection_field"],
                variables={"filterBy": filterBy},
                page_size=cfg["page_size"],
            )

            for n in nodes:
                n["event_type"] = "audit_log"

            end_offset = {"cursor": self._fmt(now)}
            return iter(self._to_bronze(nodes, now)), end_offset

        # ─────────────────────────────────────────────────────────────────────────

        def _read_detections(
            self,
            start_offset: dict | None,
            now: datetime,
        ) -> tuple[Iterator[dict], dict]:
            """
            REPLACES: collect_detections() from notebook Step 11.

            Offset shape:
                None              → initial (inLast=historical_days, cursor=None)
                {"cursor": "..."}  → incremental (resume from saved endCursor)

            NOTE ON CURSOR SAVING:
            The original Splunk TA specifies that the endCursor should be saved
            after every page to the checkpoint Delta table. 
            The framework saves the offset only after read_table() returns. 

            This means a mid-run cluster crash restarts
            from the beginning of the inLast window. No data is lost because
            the window is rolling — it just re-fetches. For very large
            environments, lower historical_days in EVENT_CONFIGS and run more
            frequently to reduce re-fetch scope.
            """
            cfg               = self._configs["detection"]
            fv                = cfg["filter_variables"]
            inc               = cfg["incremental"]
            include_triggering = cfg["include_triggering_events"]
            page_size          = cfg["page_size"] if include_triggering else 500

            resume_cursor = start_offset.get("cursor") if start_offset else None

            filterBy: dict = {
                "severity":  fv["severity"],
                "createdAt": {
                    "inLast": {
                        "amount": inc["historical_days"],
                        "unit":   "DurationFilterValueUnitDays",
                    }
                },
            }
            if fv.get("projectId"):
                filterBy["projectId"] = fv["projectId"]

            variables: dict = {
                "filterBy":                filterBy,
                "orderBy":                 cfg["order_by"],
                "includeTriggeringEvents": include_triggering,
                "first":                   page_size,
                "after":                   resume_cursor,
            }

            # ── Manual pagination — tracks last cursor ────────────────────────────
            nodes: list[dict]      = []
            last_cursor: str | None = resume_cursor

            while True:
                data       = self._client.execute(query=cfg["query"], variables=variables)
                connection = data.get(cfg["connection_field"], {})
                batch      = [n for n in connection.get("nodes", []) if isinstance(n, dict)]
                nodes.extend(batch)

                page_info  = connection.get("pageInfo", {})
                has_next   = bool(page_info.get("hasNextPage"))
                end_cursor = page_info.get("endCursor")

                if end_cursor:
                    last_cursor = end_cursor
                if not has_next or not (isinstance(end_cursor, str) and end_cursor):
                    break
                variables["after"] = end_cursor

            for n in nodes:
                n["event_type"] = "detection"

            end_offset = {
                "cursor": last_cursor or (start_offset.get("cursor") if start_offset else None)
            }
            return iter(self._to_bronze(nodes, now)), end_offset

        @staticmethod
        def python_sortable_id(
            record: dict,
            time_value: datetime,
            hash_column_values: Optional[List] = None,
            n_hash_chars: int = 11,
        ):
            # ── Step 1: time prefix (same as Spark)
            epoch = datetime(1970, 1, 1, tzinfo=timezone.utc)

            if time_value.tzinfo is None:
                time_value = time_value.replace(tzinfo=timezone.utc)

            micros = int((time_value - epoch).total_seconds() * 1_000_000)
            prefix = format(micros, "x")   # hex string

            # ── Step 2: hash input (match Spark intent)
            if hash_column_values and len(hash_column_values) > 0:
                # mimic Spark sorting of expressions
                values = sorted(hash_column_values, key=lambda x: str(x))
            else:
                values = [time_value]

            hash_input = "|".join(str(v) for v in values)
            hash_hex = hashlib.sha256(hash_input.encode()).hexdigest()

            suffix = hash_hex[-n_hash_chars:]

            return prefix + suffix

        # ─────────────────────────────────────────────────────────────────────────
        # Shared helpers
        # ─────────────────────────────────────────────────────────────────────────


        def _to_bronze(self, nodes: list[dict], collected_at: datetime) -> list[dict]:
            rows = []

            for n in nodes:
                event_type = n.get("event_type")

                # ── derive event time ─────────────────────────────────────────
                if event_type == "issue":
                    time_val = n.get("createdAt")
                elif event_type == "vulnerability_finding":
                    time_val = n.get("firstDetectedAt")
                elif event_type == "audit_log":
                    time_val = n.get("timestamp")
                elif event_type == "detection":
                    time_val = n.get("createdAt")
                else:
                    time_val = None

                # convert string → datetime
                if isinstance(time_val, str):
                    try:
                        time_val = datetime.fromisoformat(time_val.replace("Z", "+00:00"))
                    except Exception:
                        time_val = None

                # fallback
                if not time_val:
                    time_val = collected_at

                record_id = str(n.get("id", ""))

                # ── generate lw_id ─────────────────────────────────────────
                lw_id = self.python_sortable_id(
                    record={"record_id": record_id},
                    time_value=time_val,
                    hash_column_values=[record_id],
                )

                rows.append({
                    "lw_id": lw_id,
                    "time": time_val,
                    #"_raw_json": json.dumps(n, default=str),  
                    "_raw_json": n,
                    "collected_at": collected_at,
                    "event_type": event_type,
                    "record_id": record_id,
                    "_metadata": None 
                })

            return rows

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported: {TABLES}"
                )

        @staticmethod
        def _fmt(dt: datetime) -> str:
            """ISO-8601 UTC string with Z suffix — same as fmt() in notebook Step 5."""
            return dt.strftime("%Y-%m-%dT%H:%M:%SZ")

        @staticmethod
        def _parse_ts(s: str) -> datetime:
            """Parse ISO-8601 string → datetime — same as parse_ts() in notebook Step 5."""
            return datetime.fromisoformat(s.replace("Z", "+00:00"))


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = WizLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
