# ==============================================================================
# Merged Lakeflow Source: google_workspace
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import (
    Any,
    Iterator,
    Optional,
    Sequence,
)
import json

from __future__ import annotations
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib.parse import parse_qs, urlparse
import base64
import threading


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/google_workspace/google_workspace_mock_api.py
    ########################################################

    MOCK_CUSTOMER_ID = "C0mock0001"
    MOCK_DOMAIN      = "acme-corp.com"

    _PAGE_SIZE = 3   # intentionally small to exercise multi-page pagination


    # ── response / session ────────────────────────────────────────────────────────

    class GoogleWorkspaceMockResponse:
        """Mimics ``requests.Response``."""

        __slots__ = ("status_code", "_body")

        def __init__(self, status_code: int, body) -> None:
            self.status_code = status_code
            self._body = body

        def json(self):
            return self._body

        def raise_for_status(self):
            if self.status_code >= 400:
                raise RuntimeError(f"HTTP {self.status_code}: {self._body}")


    class GoogleWorkspaceMockSession:
        """Drop-in for ``requests.Session``.  Handles GET + POST (token endpoint)."""

        def __init__(self, api: "GoogleWorkspaceMockAPI") -> None:
            self.headers: dict = {}
            self._api = api

        def get(self, url: str, params=None, timeout=None) -> GoogleWorkspaceMockResponse:
            parsed = urlparse(url)
            qs = parse_qs(parsed.query, keep_blank_values=True)
            flat_qs: dict = {k: v[0] for k, v in qs.items()}
            if params:
                flat_qs.update({k: str(v) for k, v in params.items()})
            return self._api.handle_get(parsed.path, flat_qs)

        def post(self, url: str, data=None, json=None, timeout=None) -> GoogleWorkspaceMockResponse:
            # OAuth2 token endpoint
            return GoogleWorkspaceMockResponse(200, {
                "access_token": "mock-gws-token",
                "token_type":   "Bearer",
                "expires_in":   3600,
            })


    # ── mock API ──────────────────────────────────────────────────────────────────

    class GoogleWorkspaceMockAPI:
        """In-memory Google Workspace Directory API with seeded data.

        Seeded data
        ~~~~~~~~~~~
        users          8  (mix of admins, suspended, regular)
        groups         4
        group_members  6  (2 per first 3 groups)
        org_units      4  (root + 3 sub-units)
        roles          4  (2 system + 2 custom)
        role_assignments 5
        """

        def __init__(self) -> None:
            cid = MOCK_CUSTOMER_ID
            dom = MOCK_DOMAIN

            # ── users ─────────────────────────────────────────────────────────
            self._users = [
                {
                    "id": f"user-{i:04d}",
                    "primaryEmail":  f"user{i}@{dom}",
                    "name": {
                        "fullName":   f"User {i} Lastname",
                        "givenName":  f"User{i}",
                        "familyName": "Lastname",
                    },
                    "isAdmin":       (i == 0),
                    "suspended":     (i == 7),
                    "orgUnitPath":   ["/Engineering", "/Marketing", "/Finance", "/IT"][i % 4],
                    "lastLoginTime": f"2025-0{(i % 9) + 1}-15T10:00:00.000Z",
                    "creationTime":  f"2023-0{(i % 9) + 1}-01T08:00:00.000Z",
                    "customerId":    cid,
                }
                for i in range(8)
            ]

            # ── groups ────────────────────────────────────────────────────────
            self._groups = [
                {
                    "id":                 f"group-{i:04d}",
                    "email":              f"{name}@{dom}",
                    "name":               name.replace("-", " ").title(),
                    "description":        f"All {name.replace('-', ' ')} members",
                    "directMembersCount": str(2),
                    "adminCreated":       True,
                    "customerId":         cid,
                }
                for i, name in enumerate(["engineering", "marketing", "finance", "it-ops"])
            ]

            # ── group_members ─────────────────────────────────────────────────
            # 2 members per first 3 groups
            self._group_members: dict[str, list] = {}
            for g_idx in range(3):
                gid = f"group-{g_idx:04d}"
                self._group_members[gid] = [
                    {
                        "id":      f"user-{g_idx * 2 + m:04d}",
                        "email":   f"user{g_idx * 2 + m}@{dom}",
                        "role":    "MEMBER",
                        "type":    "USER",
                        "status":  "ACTIVE",
                        "groupId": gid,
                    }
                    for m in range(2)
                ]

            # ── org_units ─────────────────────────────────────────────────────
            self._org_units = [
                {
                    "orgUnitId":         "/id:root",
                    "name":              "acme-corp.com",
                    "orgUnitPath":       "/",
                    "parentOrgUnitPath": "",
                    "description":       "Root org unit",
                    "blockInheritance":  False,
                    "customerId":        cid,
                },
                *[
                    {
                        "orgUnitId":         f"/id:ou-{i:04d}",
                        "name":              name,
                        "orgUnitPath":       f"/{name}",
                        "parentOrgUnitPath": "/",
                        "description":       f"{name} department",
                        "blockInheritance":  False,
                        "customerId":        cid,
                    }
                    for i, name in enumerate(["Engineering", "Marketing", "Finance"], start=1)
                ],
            ]

            # ── roles ─────────────────────────────────────────────────────────
            self._roles = [
                {
                    "roleId":            "role-0001",
                    "roleName":          "_SEED_ADMIN_ROLE",
                    "roleDescription":   "Super Admin",
                    "isSuperAdminRole":  True,
                    "isSystemRole":      True,
                    "customerId":        cid,
                },
                {
                    "roleId":            "role-0002",
                    "roleName":          "_USER_MANAGEMENT_ROLE",
                    "roleDescription":   "User Management",
                    "isSuperAdminRole":  False,
                    "isSystemRole":      True,
                    "customerId":        cid,
                },
                {
                    "roleId":            "role-0003",
                    "roleName":          "Security Reviewer",
                    "roleDescription":   "Read-only security audit role",
                    "isSuperAdminRole":  False,
                    "isSystemRole":      False,
                    "customerId":        cid,
                },
                {
                    "roleId":            "role-0004",
                    "roleName":          "Help Desk Admin",
                    "roleDescription":   "Resets passwords and unlocks accounts",
                    "isSuperAdminRole":  False,
                    "isSystemRole":      False,
                    "customerId":        cid,
                },
            ]

            # ── role_assignments ──────────────────────────────────────────────
            self._role_assignments = [
                {
                    "roleAssignmentId": f"ra-{i:04d}",
                    "roleId":           ["role-0001", "role-0002", "role-0003",
                                         "role-0004", "role-0003"][i],
                    "assignedTo":       f"user-{i:04d}",
                    "scopeType":        "CUSTOMER",
                    "orgUnitId":        "",
                    "customerId":       cid,
                }
                for i in range(5)
            ]

        # ── pagination ────────────────────────────────────────────────────────

        def _paginate(self, records: list, params: dict, next_key: str) -> GoogleWorkspaceMockResponse:
            """Return one page; embed nextPageToken in response if more remain."""
            token = params.get("pageToken", "0")
            offset = int(token) if token.isdigit() else 0
            page = records[offset: offset + _PAGE_SIZE]
            body = {next_key: page}
            next_offset = offset + _PAGE_SIZE
            if next_offset < len(records):
                body["nextPageToken"] = str(next_offset)
            return GoogleWorkspaceMockResponse(200, body)

        # ── routing ───────────────────────────────────────────────────────────

        def handle_get(self, path: str, params: dict) -> GoogleWorkspaceMockResponse:
            parts = [p for p in path.strip("/").split("/") if p]
            # /admin/directory/v1/users
            if parts == ["admin", "directory", "v1", "users"]:
                return self._paginate(self._users, params, "users")

            # /admin/directory/v1/groups
            if parts == ["admin", "directory", "v1", "groups"]:
                return self._paginate(self._groups, params, "groups")

            # /admin/directory/v1/groups/{groupKey}/members
            if (len(parts) == 6 and parts[:4] == ["admin", "directory", "v1", "groups"]
                    and parts[5] == "members"):
                group_id = parts[4]
                members = self._group_members.get(group_id, [])
                return GoogleWorkspaceMockResponse(200, {"members": members})

            # /admin/directory/v1/customer/{customerId}/orgunits
            if (len(parts) == 6 and parts[:4] == ["admin", "directory", "v1", "customer"]
                    and parts[5] == "orgunits"):
                return GoogleWorkspaceMockResponse(200, {"organizationUnits": self._org_units})

            # /admin/directory/v1/customer/{customerId}/roles
            if (len(parts) == 6 and parts[:4] == ["admin", "directory", "v1", "customer"]
                    and parts[5] == "roles"):
                return self._paginate(self._roles, params, "items")

            # /admin/directory/v1/customer/{customerId}/roleassignments
            if (len(parts) == 6 and parts[:4] == ["admin", "directory", "v1", "customer"]
                    and parts[5] == "roleassignments"):
                return self._paginate(self._role_assignments, params, "items")

            return GoogleWorkspaceMockResponse(404, {"error": f"No route for GET {path}"})

        def get_session(self) -> GoogleWorkspaceMockSession:
            return GoogleWorkspaceMockSession(self)


    # ── singleton management ──────────────────────────────────────────────────────

    _INSTANCE: Optional[GoogleWorkspaceMockAPI] = None
    _INSTANCE_LOCK = threading.Lock()


    def get_mock_api() -> GoogleWorkspaceMockAPI:
        global _INSTANCE  # noqa: PLW0603
        with _INSTANCE_LOCK:
            if _INSTANCE is None:
                _INSTANCE = GoogleWorkspaceMockAPI()
            return _INSTANCE


    def reset_mock_api() -> GoogleWorkspaceMockAPI:
        global _INSTANCE  # noqa: PLW0603
        with _INSTANCE_LOCK:
            _INSTANCE = GoogleWorkspaceMockAPI()
            return _INSTANCE


    ########################################################
    # src/databricks/labs/community_connector/sources/google_workspace/google_workspace_schemas.py
    ########################################################

    SUPPORTED_TABLES = [
        "users",
        "groups",
        "group_members",
        "org_units",
        "roles",
        "role_assignments",
    ]

    TABLE_SCHEMAS = {
        "users": StructType([
            StructField("id",               StringType(),  False),
            StructField("primary_email",    StringType(),  True),
            StructField("full_name",        StringType(),  True),
            StructField("given_name",       StringType(),  True),
            StructField("family_name",      StringType(),  True),
            StructField("is_admin",         BooleanType(), True),
            StructField("is_suspended",     BooleanType(), True),
            StructField("org_unit_path",    StringType(),  True),
            StructField("last_login_time",  StringType(),  True),
            StructField("creation_time",    StringType(),  True),
            StructField("customer_id",      StringType(),  True),
        ]),
        "groups": StructType([
            StructField("id",               StringType(),  False),
            StructField("email",            StringType(),  True),
            StructField("name",             StringType(),  True),
            StructField("description",      StringType(),  True),
            StructField("direct_members_count", StringType(), True),
            StructField("admin_created",    BooleanType(), True),
            StructField("customer_id",      StringType(),  True),
        ]),
        "group_members": StructType([
            StructField("id",               StringType(),  False),
            StructField("email",            StringType(),  True),
            StructField("role",             StringType(),  True),
            StructField("type",             StringType(),  True),
            StructField("status",           StringType(),  True),
            StructField("group_id",         StringType(),  True),
        ]),
        "org_units": StructType([
            StructField("org_unit_id",      StringType(),  False),
            StructField("name",             StringType(),  True),
            StructField("org_unit_path",    StringType(),  True),
            StructField("parent_org_unit_path", StringType(), True),
            StructField("description",      StringType(),  True),
            StructField("block_inheritance", BooleanType(), True),
            StructField("customer_id",      StringType(),  True),
        ]),
        "roles": StructType([
            StructField("role_id",          StringType(),  False),
            StructField("role_name",        StringType(),  True),
            StructField("role_description", StringType(),  True),
            StructField("is_super_admin_role", BooleanType(), True),
            StructField("is_system_role",   BooleanType(), True),
            StructField("customer_id",      StringType(),  True),
        ]),
        "role_assignments": StructType([
            StructField("role_assignment_id", StringType(), False),
            StructField("role_id",            StringType(), True),
            StructField("assigned_to",        StringType(), True),
            StructField("scope_type",         StringType(), True),
            StructField("org_unit_id",        StringType(), True),
            StructField("customer_id",        StringType(), True),
        ]),
    }

    # All tables are snapshot — the Directory API does not expose a change cursor.
    # Re-run the pipeline to pick up the latest state.
    TABLE_METADATA = {
        "users": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "groups": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "group_members": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "org_units": {
            "ingestion_type": "snapshot",
            "primary_keys": ["org_unit_id"],
        },
        "roles": {
            "ingestion_type": "snapshot",
            "primary_keys": ["role_id"],
        },
        "role_assignments": {
            "ingestion_type": "snapshot",
            "primary_keys": ["role_assignment_id"],
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/google_workspace/google_workspace.py
    ########################################################

    _DIRECTORY_BASE = "https://admin.googleapis.com/admin/directory/v1"
    _TOKEN_URL      = "https://oauth2.googleapis.com/token"
    _SCOPES = " ".join([
        "https://www.googleapis.com/auth/admin.directory.user.readonly",
        "https://www.googleapis.com/auth/admin.directory.group.readonly",
        "https://www.googleapis.com/auth/admin.directory.orgunit.readonly",
        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly",
    ])


    class GoogleWorkspaceLakeflowConnect(LakeflowConnect):

        def __init__(self, options: dict[str, str]) -> None:
            sa_json = options.get("service_account_json", "")
            if not sa_json:
                raise ValueError(
                    "Google Workspace connector requires 'service_account_json' in options. "
                    "Pass the full service account key JSON as a string, or 'mock' for demo mode."
                )

            self._customer_id = options.get("customer_id", "my_customer")
            self._domain      = options.get("domain", "")

            if sa_json == "mock":
                self._session = get_mock_api().get_session()
            else:
                self._session = self._build_session(sa_json, options.get("admin_email", ""))

        # ── session factory (real mode only) ──────────────────────────────────

        def _build_session(self, sa_json_str: str, admin_email: str):
            """Build a requests.Session with a service-account Bearer token.

            Uses the google-auth library when available; falls back to a manual
            JWT flow so the connector works without the google-auth extras package.
            """
            import requests

            try:
                import google.auth.transport.requests as gtr
                from google.oauth2 import service_account

                creds = service_account.Credentials.from_service_account_info(
                    json.loads(sa_json_str),
                    scopes=_SCOPES.split(),
                    subject=admin_email or None,
                )
                creds.refresh(gtr.Request())
                token = creds.token
            except ImportError:
                # Manual JWT → access-token exchange (no google-auth dependency)
                import time, base64, hashlib, hmac

                sa = json.loads(sa_json_str)
                now = int(time.time())
                header  = {"alg": "RS256", "typ": "JWT"}
                payload = {
                    "iss":   sa["client_email"],
                    "sub":   admin_email or sa["client_email"],
                    "scope": _SCOPES,
                    "aud":   _TOKEN_URL,
                    "iat":   now,
                    "exp":   now + 3600,
                }

                def _b64(obj):
                    return base64.urlsafe_b64encode(
                        json.dumps(obj, separators=(",", ":")).encode()
                    ).rstrip(b"=").decode()

                unsigned = f"{_b64(header)}.{_b64(payload)}"

                from cryptography.hazmat.primitives import hashes, serialization
                from cryptography.hazmat.primitives.asymmetric import padding

                private_key = serialization.load_pem_private_key(
                    sa["private_key"].encode(), password=None
                )
                sig = private_key.sign(unsigned.encode(), padding.PKCS1v15(), hashes.SHA256())
                jwt = f"{unsigned}.{base64.urlsafe_b64encode(sig).rstrip(b'=').decode()}"

                resp = requests.post(_TOKEN_URL,
                                     data={"grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
                                           "assertion": jwt},
                                     timeout=30)
                resp.raise_for_status()
                token = resp.json()["access_token"]

            session = requests.Session()
            session.headers.update({"Authorization": f"Bearer {token}"})
            return session

        # ── LakeflowConnect interface ─────────────────────────────────────────

        def list_tables(self) -> list[str]:
            return SUPPORTED_TABLES.copy()

        def get_table_schema(self, table_name: str, table_options: dict) -> StructType:
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict) -> dict:
            if table_name not in TABLE_METADATA:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_METADATA[table_name]

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict
        ) -> tuple[Iterator[dict], dict]:
            dispatch = {
                "users":            self._read_users,
                "groups":           self._read_groups,
                "group_members":    self._read_group_members,
                "org_units":        self._read_org_units,
                "roles":            self._read_roles,
                "role_assignments": self._read_role_assignments,
            }
            if table_name not in dispatch:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return dispatch[table_name](start_offset, table_options)

        # ── pagination helper ─────────────────────────────────────────────────

        def _paginate(self, url: str, params: dict, data_key: str) -> list[dict]:
            """Follow nextPageToken until all pages are consumed."""
            results = []
            next_token = None
            while True:
                req_params = dict(params)
                if next_token:
                    req_params["pageToken"] = next_token
                resp = self._session.get(url, params=req_params, timeout=30)
                resp.raise_for_status()
                body = resp.json()
                results.extend(body.get(data_key, []))
                next_token = body.get("nextPageToken")
                if not next_token:
                    break
            return results

        # ── table readers ─────────────────────────────────────────────────────

        def _read_users(self, start_offset: dict, table_options: dict):
            params = {"maxResults": 500}
            if self._domain:
                params["domain"] = self._domain
            else:
                params["customer"] = self._customer_id

            raw = self._paginate(f"{_DIRECTORY_BASE}/users", params, "users")
            records = [
                {
                    "id":              u.get("id"),
                    "primary_email":   u.get("primaryEmail"),
                    "full_name":       (u.get("name") or {}).get("fullName"),
                    "given_name":      (u.get("name") or {}).get("givenName"),
                    "family_name":     (u.get("name") or {}).get("familyName"),
                    "is_admin":        u.get("isAdmin", False),
                    "is_suspended":    u.get("suspended", False),
                    "org_unit_path":   u.get("orgUnitPath"),
                    "last_login_time": u.get("lastLoginTime"),
                    "creation_time":   u.get("creationTime"),
                    "customer_id":     u.get("customerId"),
                }
                for u in raw
            ]
            return iter(records), {}

        def _read_groups(self, start_offset: dict, table_options: dict):
            params = {"maxResults": 200}
            if self._domain:
                params["domain"] = self._domain
            else:
                params["customer"] = self._customer_id

            raw = self._paginate(f"{_DIRECTORY_BASE}/groups", params, "groups")
            records = [
                {
                    "id":                  g.get("id"),
                    "email":               g.get("email"),
                    "name":                g.get("name"),
                    "description":         g.get("description"),
                    "direct_members_count": g.get("directMembersCount"),
                    "admin_created":       g.get("adminCreated", False),
                    "customer_id":         g.get("customerId"),
                }
                for g in raw
            ]
            return iter(records), {}

        def _read_group_members(self, start_offset: dict, table_options: dict):
            """Fetch members for every group found in the domain."""
            _, _ = self._read_groups({}, table_options)

            groups_params = {"maxResults": 200}
            if self._domain:
                groups_params["domain"] = self._domain
            else:
                groups_params["customer"] = self._customer_id

            groups_raw = self._paginate(f"{_DIRECTORY_BASE}/groups", groups_params, "groups")

            all_members = []
            for group in groups_raw:
                group_id = group.get("id")
                url = f"{_DIRECTORY_BASE}/groups/{group_id}/members"
                resp = self._session.get(url, timeout=30)
                if resp.status_code == 404:
                    continue
                resp.raise_for_status()
                for m in resp.json().get("members", []):
                    all_members.append({
                        "id":       m.get("id"),
                        "email":    m.get("email"),
                        "role":     m.get("role"),
                        "type":     m.get("type"),
                        "status":   m.get("status"),
                        "group_id": group_id,
                    })

            return iter(all_members), {}

        def _read_org_units(self, start_offset: dict, table_options: dict):
            url = f"{_DIRECTORY_BASE}/customer/{self._customer_id}/orgunits"
            resp = self._session.get(url, params={"type": "all"}, timeout=30)
            resp.raise_for_status()
            raw = resp.json().get("organizationUnits", [])
            records = [
                {
                    "org_unit_id":          o.get("orgUnitId"),
                    "name":                 o.get("name"),
                    "org_unit_path":        o.get("orgUnitPath"),
                    "parent_org_unit_path": o.get("parentOrgUnitPath"),
                    "description":          o.get("description"),
                    "block_inheritance":    o.get("blockInheritance", False),
                    "customer_id":          o.get("customerId"),
                }
                for o in raw
            ]
            return iter(records), {}

        def _read_roles(self, start_offset: dict, table_options: dict):
            url = f"{_DIRECTORY_BASE}/customer/{self._customer_id}/roles"
            raw = self._paginate(url, {"maxResults": 100}, "items")
            records = [
                {
                    "role_id":             r.get("roleId"),
                    "role_name":           r.get("roleName"),
                    "role_description":    r.get("roleDescription"),
                    "is_super_admin_role": r.get("isSuperAdminRole", False),
                    "is_system_role":      r.get("isSystemRole", False),
                    "customer_id":         self._customer_id,
                }
                for r in raw
            ]
            return iter(records), {}

        def _read_role_assignments(self, start_offset: dict, table_options: dict):
            url = f"{_DIRECTORY_BASE}/customer/{self._customer_id}/roleassignments"
            raw = self._paginate(url, {"maxResults": 200}, "items")
            records = [
                {
                    "role_assignment_id": ra.get("roleAssignmentId"),
                    "role_id":            ra.get("roleId"),
                    "assigned_to":        ra.get("assignedTo"),
                    "scope_type":         ra.get("scopeType"),
                    "org_unit_id":        ra.get("orgUnitId", ""),
                    "customer_id":        self._customer_id,
                }
                for ra in raw
            ]
            return iter(records), {}


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = GoogleWorkspaceLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
