# ==============================================================================
# Merged Lakeflow Source: snyk
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import (
    Any,
    Iterator,
    Optional,
    Sequence,
)
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from urllib.parse import parse_qs, urlparse
from pyspark.sql.types import *
import base64
import uuid


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current start offset, or None on the first call.
                    PySpark's ``DataSourceStreamReader.latestOffset()`` does not
                    pass this yet, so the framework always sends None for now.
                    Connectors may use it to implement windowed batching when
                    called directly.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/snyk/snyk_mock_api.py
    ########################################################

    MOCK_ORG_ID = "org-mock-0001"

    _PAGE_SIZE = 3  # intentionally small to exercise multi-page pagination in tests


    # ── helpers ──────────────────────────────────────────────────────────────────

    def _now() -> datetime:
        return datetime.now(timezone.utc)


    def _iso(dt: datetime) -> str:
        return dt.isoformat()


    # ── response / session ───────────────────────────────────────────────────────

    class SnykMockResponse:
        """Mimics ``requests.Response`` with ``.status_code``, ``.json()``, and ``.raise_for_status()``."""

        __slots__ = ("status_code", "_body")

        def __init__(self, status_code: int, body) -> None:
            self.status_code = status_code
            self._body = body

        def json(self):
            return self._body

        def raise_for_status(self):
            if self.status_code >= 400:
                raise RuntimeError(f"HTTP {self.status_code}: {self._body}")


    class SnykMockSession:
        """Drop-in replacement for ``requests.Session`` backed by ``SnykMockAPI``.

        Parses the full URL (including embedded query params from ``links.next``
        follow-up requests) and delegates to the API instance.
        """

        def __init__(self, api: "SnykMockAPI") -> None:
            self.headers: dict = {}
            self._api = api

        def get(self, url: str, params=None, timeout=None) -> SnykMockResponse:
            parsed = urlparse(url)
            qs = parse_qs(parsed.query, keep_blank_values=True)
            flat_qs: dict = {k: v[0] for k, v in qs.items()}
            if params:
                flat_qs.update({k: str(v) for k, v in params.items()})
            return self._api.handle_get(parsed.path, flat_qs)


    # ── mock API ─────────────────────────────────────────────────────────────────

    class SnykMockAPI:
        """In-memory Snyk API with seeded data for all five tables.

        Tables seeded
        ~~~~~~~~~~~~~
        organizations  1 org
        projects       5 projects  (pagination: ceil(5/3) = 2 pages)
        issues        10 issues    (CDC via ``updated_at``; supports ``updated_after``)
        targets        5 targets
        users          5 users
        vulnerabilities 10 vulnerabilities
        """

        def __init__(self) -> None:
            base = _now() - timedelta(hours=2)

            # ── organizations (V1 format) ─────────────────────────────────────
            self._orgs = [
                {
                    "id": MOCK_ORG_ID,
                    "name": "Acme Security",
                    "slug": "acme-security",
                    "url": "https://app.snyk.io/org/acme-security",
                }
            ]

            # ── projects ─────────────────────────────────────────────────────
            self._projects = [
                self._jsonapi(
                    f"proj-{i:04d}", "project",
                    {
                        "name": f"acme/service-{i}",
                        "status": "active",
                        "origin": "github",
                        "created": _iso(base + timedelta(hours=i)),
                    },
                    {"organization": {"data": {"id": MOCK_ORG_ID}}},
                )
                for i in range(5)
            ]

            # ── issues ───────────────────────────────────────────────────────
            self._issues = [
                self._jsonapi(
                    str(uuid.UUID(int=i)), "issue",
                    {
                        "title": f"Security issue {i}",
                        "status": "open",
                        "effective_severity_level": ["low", "medium", "high", "critical"][i % 4],
                        "ignored": False,
                        "created_at": _iso(base + timedelta(minutes=i * 5)),
                        "updated_at": _iso(base + timedelta(minutes=i * 5)),
                        "tool": ["snyk-open-source", "snyk-code"][i % 2],
                    },
                    {
                        "organization": {"data": {"id": MOCK_ORG_ID}},
                        "scan_item": {"data": {"id": f"proj-{i % 5:04d}"}},
                    },
                )
                for i in range(10)
            ]

            # ── targets ──────────────────────────────────────────────────────
            self._targets = [
                self._jsonapi(
                    f"target-{i:04d}", "target",
                    {
                        "display_name": f"github.com/acme/repo-{i}",
                        "url": f"https://github.com/acme/repo-{i}",
                    },
                    {"organization": {"data": {"id": MOCK_ORG_ID}}},
                )
                for i in range(5)
            ]

            # ── users ─────────────────────────────────────────────────────────
            self._users = [
                self._jsonapi(
                    f"user-{i:04d}", "user",
                    {
                        "name": f"User {i}",
                        "email": f"user{i}@acme.io",
                        "username": f"user{i}",
                    },
                    {"organization": {"data": {"id": MOCK_ORG_ID}}},
                )
                for i in range(5)
            ]

            # ── vulnerabilities ───────────────────────────────────────────────
            _packages = ["lodash", "axios", "express", "moment", "requests"]
            _severities = ["low", "medium", "high", "critical"]
            self._vulnerabilities = [
                self._jsonapi(
                    f"vuln-{i:04d}", "vulnerability",
                    {
                        "title": f"Vulnerability in {_packages[i % 5]}",
                        "severity": _severities[i % 4],
                        "status": "open",
                        "cve": f"CVE-2024-{1000 + i}",
                        "cvss_score": round(3.0 + i * 0.6, 1),
                        "package": _packages[i % 5],
                        "version": "1.0.0",
                        "fixed_in": "1.0.1",
                        "disclosure_time": _iso(base + timedelta(days=i)),
                        "publication_time": _iso(base + timedelta(days=i, hours=1)),
                    },
                    {
                        "organization": {"data": {"id": MOCK_ORG_ID}},
                        "project": {"data": {"id": f"proj-{i % 5:04d}"}},
                    },
                )
                for i in range(10)
            ]

        # ── static helpers ────────────────────────────────────────────────────

        @staticmethod
        def _jsonapi(id_: str, type_: str, attributes: dict, relationships: dict) -> dict:
            """Wrap fields in JSON:API envelope."""
            return {
                "id": id_,
                "type": type_,
                "attributes": attributes,
                "relationships": relationships,
            }

        # ── pagination ────────────────────────────────────────────────────────

        def _paginate(self, path: str, records: list, params: dict) -> SnykMockResponse:
            """Return one page of records with a ``links.next`` cursor if more remain."""
            offset = int(params.get("starting_after", 0))
            limit = min(int(params.get("limit", _PAGE_SIZE)), _PAGE_SIZE)
            page = records[offset: offset + limit]
            links: dict = {}
            next_offset = offset + limit
            if next_offset < len(records):
                version = params.get("version", "2024-10-15")
                links["next"] = f"{path}?version={version}&limit={limit}&starting_after={next_offset}"
            return SnykMockResponse(200, {"data": page, "links": links})

        # ── request routing ───────────────────────────────────────────────────

        def handle_get(self, path: str, params: dict) -> SnykMockResponse:
            """Route a GET request and return the appropriate mock response."""
            # V1: GET /v1/orgs
            if path.rstrip("/") == "/v1/orgs":
                return SnykMockResponse(200, {"orgs": self._orgs})

            # REST: GET /rest/orgs/{org_id}/{resource}
            parts = [p for p in path.split("/") if p]
            # ["rest", "orgs", "{org_id}", "{resource}"]
            if len(parts) >= 4 and parts[0] == "rest" and parts[1] == "orgs":
                org_id = parts[2]
                resource = parts[3]

                if org_id != MOCK_ORG_ID:
                    return SnykMockResponse(404, {"error": f"Org '{org_id}' not found"})

                resource_map: dict[str, list] = {
                    "projects": self._projects,
                    "issues": self._issues,
                    "targets": self._targets,
                    "users": self._users,
                    "vulnerabilities": self._vulnerabilities,
                }
                if resource not in resource_map:
                    return SnykMockResponse(404, {"error": f"Unknown resource: '{resource}'"})

                records = resource_map[resource]

                # issues supports updated_after filter for CDC
                if resource == "issues" and params.get("updated_after"):
                    cutoff = params["updated_after"]
                    records = [
                        r for r in records
                        if r["attributes"].get("updated_at", "") > cutoff
                    ]

                return self._paginate(path, records, params)

            return SnykMockResponse(404, {"error": f"No route for GET {path}"})

        def get_session(self) -> SnykMockSession:
            """Return a new session backed by this API instance."""
            return SnykMockSession(self)


    # ── singleton management ──────────────────────────────────────────────────────
    # No threading.Lock here — threading.Lock is not picklable and the merge script
    # inlines this module inside register_lakeflow_source, which cloudpickle captures
    # entirely when serializing the DataSource for Spark workers.

    _INSTANCE: Optional[SnykMockAPI] = None


    def get_mock_api() -> SnykMockAPI:
        """Return the singleton mock API instance, creating it on first call."""
        global _INSTANCE  # noqa: PLW0603
        if _INSTANCE is None:
            _INSTANCE = SnykMockAPI()
        return _INSTANCE


    def reset_mock_api() -> SnykMockAPI:
        """Reset the singleton — call at the start of each test run."""
        global _INSTANCE  # noqa: PLW0603
        _INSTANCE = SnykMockAPI()
        return _INSTANCE


    ########################################################
    # src/databricks/labs/community_connector/sources/snyk/snyk_schemas.py
    ########################################################

    SUPPORTED_TABLES = ["organizations", "projects", "issues", "targets", "users", "vulnerabilities", "events"]

    TABLE_SCHEMAS = {
        "organizations": StructType([
            StructField("id", StringType(), False),
            StructField("name", StringType(), True),
            StructField("slug", StringType(), True),
            StructField("url", StringType(), True),
        ]),
        "projects": StructType([
            StructField("id", StringType(), False),
            StructField("type", StringType(), True),
            StructField("name", StringType(), True),
            StructField("status", StringType(), True),
            StructField("origin", StringType(), True),
            StructField("created", StringType(), True),
            StructField("organization_id", StringType(), True),
        ]),
        "issues": StructType([
            StructField("id", StringType(), False),
            StructField("type", StringType(), True),
            StructField("title", StringType(), True),
            StructField("status", StringType(), True),
            StructField("effective_severity_level", StringType(), True),
            StructField("ignored", BooleanType(), True),
            StructField("created_at", StringType(), True),
            StructField("updated_at", StringType(), True),
            StructField("organization_id", StringType(), True),
            StructField("scan_item_id", StringType(), True),
            StructField("tool", StringType(), True),
        ]),
        "targets": StructType([
            StructField("id", StringType(), False),
            StructField("type", StringType(), True),
            StructField("display_name", StringType(), True),
            StructField("url", StringType(), True),
            StructField("organization_id", StringType(), True),
        ]),
        "users": StructType([
            StructField("id", StringType(), False),
            StructField("type", StringType(), True),
            StructField("name", StringType(), True),
            StructField("email", StringType(), True),
            StructField("username", StringType(), True),
            StructField("organization_id", StringType(), True),
        ]),
        "vulnerabilities": StructType([
            StructField("id", StringType(), False),
            StructField("type", StringType(), True),
            StructField("title", StringType(), True),
            StructField("severity", StringType(), True),
            StructField("status", StringType(), True),
            StructField("cve", StringType(), True),
            StructField("cvss_score", DoubleType(), True),
            StructField("package", StringType(), True),
            StructField("version", StringType(), True),
            StructField("fixed_in", StringType(), True),
            StructField("disclosure_time", StringType(), True),
            StructField("publication_time", StringType(), True),
            StructField("organization_id", StringType(), True),
            StructField("project_id", StringType(), True),
        ]),
        "events": StructType([
            StructField("id", StringType(), False),
            StructField("title", StringType(), True),
            StructField("severity", StringType(), True),
            StructField("cvss_score", DoubleType(), True),
            StructField("language", StringType(), True),
            StructField("package_name", StringType(), True),
            StructField("module_name", StringType(), True),
            StructField("package_manager", StringType(), True),
            StructField("version", StringType(), True),
            StructField("primary_fixed_version", StringType(), True),
            StructField("fixed_in", StringType(), True),
            StructField("cve_ids", StringType(), True),
            StructField("exploit", StringType(), True),
            StructField("org", StringType(), True),
            StructField("project_name", StringType(), True),
            StructField("path", StringType(), True),
            StructField("is_upgradable", BooleanType(), True),
            StructField("is_patchable", BooleanType(), True),
            StructField("is_pinnable", BooleanType(), True),
            StructField("malicious", BooleanType(), True),
            StructField("disclosure_time", StringType(), True),
            StructField("publication_time", StringType(), True),
            StructField("creation_time", StringType(), True),
            StructField("modification_time", StringType(), True),
            StructField("event_type", StringType(), True),
            StructField("description", StringType(), True),
        ]),
    }

    TABLE_METADATA = {
        "organizations": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "projects": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "issues": {
            "ingestion_type": "cdc",
            "primary_keys": ["id"],
            "cursor_field": "updated_at",
        },
        "targets": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "users": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "vulnerabilities": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
        "events": {
            "ingestion_type": "snapshot",
            "primary_keys": ["id"],
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/snyk/snyk.py
    ########################################################

    _API_VERSION = "2024-10-15"
    _REST_BASE = "https://api.snyk.io/rest"
    _V1_BASE = "https://api.snyk.io/v1"


    class SnykLakeflowConnect(LakeflowConnect):

        def __init__(self, options: dict[str, str]) -> None:
            token = options.get("token")
            if not token:
                raise ValueError("Snyk connector requires 'token' in options")

            api_base_url = options.get("api_base_url", "").rstrip("/")
            self._rest_base = api_base_url or _REST_BASE.rstrip("/")
            self._v1_base = options.get("v1_base_url", _V1_BASE).rstrip("/")
            # Events endpoint lives at the host root (e.g. https://faker.host/api/events)
            self._events_base = api_base_url or _REST_BASE.rstrip("/").replace("/rest", "")
            self._mock = (token == "mock")

            # Store only picklable auth config; session is created lazily in _get_session().
            # requests.Session holds thread locks and cannot be pickled by Spark workers.
            if not self._mock:
                if api_base_url and api_base_url != _REST_BASE.rstrip("/"):
                    self._auth_headers = {
                        "Authorization": f"Bearer {token}",
                        "Accept": "application/json",
                    }
                else:
                    self._auth_headers = {
                        "Authorization": f"token {token}",
                        "Accept": "application/vnd.api+json",
                    }

        def _get_session(self):
            """Create a requests.Session on demand (not stored, so the connector stays picklable)."""
            if self._mock:
                return get_mock_api().get_session()
            import requests
            session = requests.Session()
            session.headers.update(self._auth_headers)
            return session

        def list_tables(self) -> list[str]:
            return SUPPORTED_TABLES.copy()

        def get_table_schema(self, table_name: str, table_options: dict) -> StructType:
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict) -> dict:
            if table_name not in TABLE_METADATA:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return TABLE_METADATA[table_name]

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict
        ) -> tuple[Iterator[dict], dict]:
            dispatch = {
                "organizations": self._read_organizations,
                "projects": self._read_projects,
                "issues": self._read_issues,
                "targets": self._read_targets,
                "users": self._read_users,
                "vulnerabilities": self._read_vulnerabilities,
                "events": self._read_events,
            }
            if table_name not in dispatch:
                raise ValueError(f"Unsupported table: {table_name!r}")
            return dispatch[table_name](start_offset, table_options)

        def _paginate_rest(self, url: str, params: dict) -> list[dict]:
            """Paginate Snyk REST (JSON:API) using links.next cursor."""
            session = self._get_session()
            results = []
            next_url = url
            next_params: dict | None = params

            while next_url:
                resp = session.get(next_url, params=next_params, timeout=30)
                if resp.status_code == 429:
                    # Rate-limited — wait and retry once
                    time.sleep(60)
                    resp = session.get(next_url, params=next_params, timeout=30)
                resp.raise_for_status()
                body = resp.json()
                data = body.get("data", [])
                if isinstance(data, list):
                    results.extend(data)
                elif isinstance(data, dict):
                    results.append(data)
                links = body.get("links", {})
                next_path = links.get("next")
                if next_path:
                    next_url = f"https://api.snyk.io{next_path}"
                    next_params = None  # cursor already embedded in next_path
                else:
                    break
            return results

        def _flatten_jsonapi(self, record: dict) -> dict:
            """Flatten JSON:API { id, type, attributes, relationships } to flat dict."""
            flat = {"id": record.get("id"), "type": record.get("type")}
            flat.update(record.get("attributes", {}))
            for rel_name, rel_data in (record.get("relationships") or {}).items():
                inner = rel_data.get("data") or {}
                if isinstance(inner, dict):
                    flat[f"{rel_name}_id"] = inner.get("id")
            return flat

        def _read_organizations(self, start_offset: dict, table_options: dict):
            if self._is_faker_mode:
                return iter([]), {}
            url = f"{self._v1_base}/orgs"
            resp = self._get_session().get(url, timeout=30)
            resp.raise_for_status()
            orgs_raw = resp.json().get("orgs", [])
            records = [
                {"id": o.get("id"), "name": o.get("name"),
                 "slug": o.get("slug"), "url": o.get("url")}
                for o in orgs_raw
            ]
            return iter(records), {}

        @property
        def _is_faker_mode(self) -> bool:
            """True when connected to a custom/faker host instead of the real Snyk API."""
            return self._rest_base != _REST_BASE.rstrip("/")

        def _require_org_id(self, table_options: dict, table_name: str):
            """Return the org_id, or None when running against a faker/custom host.

            For the real Snyk API, org_id is required and a missing/placeholder
            value raises ValueError.  For a custom base URL (e.g. the faker) the
            org-scoped REST endpoints don't exist, so we return None to signal
            that the caller should yield an empty result set.
            """
            org_id = table_options.get("org_id", "")
            if not org_id or org_id.startswith("<"):
                if self._is_faker_mode:
                    return None  # silently skip — faker has no org-based endpoints
                raise ValueError(
                    f"Table '{table_name}' requires 'org_id' in table_options. "
                    "Add it to table_configuration in the pipeline spec."
                )
            return org_id

        def _read_projects(self, start_offset: dict, table_options: dict):
            org_id = self._require_org_id(table_options, "projects")
            if org_id is None:
                return iter([]), {}
            url = f"{self._rest_base}/orgs/{org_id}/projects"
            params = {"version": _API_VERSION, "limit": 100}
            raw = self._paginate_rest(url, params)
            records = [self._flatten_jsonapi(r) for r in raw]
            return iter(records), {}

        def _read_issues(self, start_offset: dict, table_options: dict):
            org_id = self._require_org_id(table_options, "issues")
            if org_id is None:
                return iter([]), {}
            cursor_dt = (start_offset or {}).get("cursor")
            url = f"{self._rest_base}/orgs/{org_id}/issues"
            params: dict = {"version": _API_VERSION, "limit": 100}
            if cursor_dt:
                params["updated_after"] = cursor_dt

            raw = self._paginate_rest(url, params)
            records = [self._flatten_jsonapi(r) for r in raw]

            if not records:
                return iter([]), start_offset or {}

            max_updated = max(
                r["updated_at"] for r in records if r.get("updated_at")
            )
            new_offset = {"cursor": max_updated}
            return iter(records), new_offset if new_offset != start_offset else start_offset or {}

        def _read_targets(self, start_offset: dict, table_options: dict):
            org_id = self._require_org_id(table_options, "targets")
            if org_id is None:
                return iter([]), {}
            url = f"{self._rest_base}/orgs/{org_id}/targets"
            params = {"version": _API_VERSION, "limit": 100}
            raw = self._paginate_rest(url, params)
            records = [self._flatten_jsonapi(r) for r in raw]
            return iter(records), {}

        def _read_users(self, start_offset: dict, table_options: dict):
            org_id = self._require_org_id(table_options, "users")
            if org_id is None:
                return iter([]), {}
            url = f"{self._rest_base}/orgs/{org_id}/users"
            params = {"version": _API_VERSION, "limit": 100}
            raw = self._paginate_rest(url, params)
            records = [self._flatten_jsonapi(r) for r in raw]
            return iter(records), {}

        def _read_vulnerabilities(self, start_offset: dict, table_options: dict):
            org_id = self._require_org_id(table_options, "vulnerabilities")
            if org_id is None:
                return iter([]), {}
            url = f"{self._rest_base}/orgs/{org_id}/vulnerabilities"
            params = {"version": _API_VERSION, "limit": 100}
            raw = self._paginate_rest(url, params)
            records = [self._flatten_jsonapi(r) for r in raw]
            return iter(records), {}

        def _read_events(self, start_offset: dict, table_options: dict):
            """Read from the /api/events NDJSON endpoint (Snyk faker / custom deployments)."""
            url = f"{self._events_base}/api/events"
            resp = self._get_session().get(url, timeout=30)
            resp.raise_for_status()
            records = []
            for line in resp.text.strip().splitlines():
                if not line.strip():
                    continue
                raw = json.loads(line)
                records.append({
                    "id": raw.get("id"),
                    "title": raw.get("title"),
                    "severity": raw.get("severity"),
                    "cvss_score": raw.get("cvssScore"),
                    "language": raw.get("language"),
                    "package_name": raw.get("packageName"),
                    "module_name": raw.get("moduleName"),
                    "package_manager": raw.get("packageManager"),
                    "version": raw.get("version"),
                    "primary_fixed_version": raw.get("primaryFixedVersion"),
                    "fixed_in": json.dumps(raw.get("fixedIn") or []),
                    "cve_ids": json.dumps(raw.get("cveIds") or []),
                    "exploit": raw.get("exploit"),
                    "org": raw.get("org"),
                    "project_name": raw.get("projectName"),
                    "path": raw.get("path"),
                    "is_upgradable": raw.get("isUpgradable"),
                    "is_patchable": raw.get("isPatchable"),
                    "is_pinnable": raw.get("isPinnable"),
                    "malicious": raw.get("malicious"),
                    "disclosure_time": raw.get("disclosureTime"),
                    "publication_time": raw.get("publicationTime"),
                    "creation_time": raw.get("creationTime"),
                    "modification_time": raw.get("modificationTime"),
                    "event_type": raw.get("eventType"),
                    "description": raw.get("description"),
                })
            return iter(records), {}


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = SnykLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowPartitionedStreamReader(DataSourceStreamReader):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def latestOffset(self):
            # PySpark does not pass the current offset to latestOffset() yet,
            # so we forward None.  Once PySpark supports it, pass the real value.
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, None)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
