# ==============================================================================
# Merged Lakeflow Source: google_sheets_docs
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import re
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib.parse import quote
import base64
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/google_sheets_docs/google_sheets_docs_schemas.py
    ########################################################

    SUPPORTED_TABLES = ["spreadsheets", "sheet_values", "documents"]

    # ---------------------------------------------------------------------------
    # Static schemas (Spark StructType) per table
    # ---------------------------------------------------------------------------

    # spreadsheets: Drive API files.list result for mimeType=spreadsheet.
    # id is the Drive file id (same as spreadsheetId for Sheets API).
    SPREADSHEETS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField("mimeType", StringType(), nullable=True),
            StructField("modifiedTime", StringType(), nullable=True),
            StructField("createdTime", StringType(), nullable=True),
        ]
    )

    # sheet_values: Default schema when not using first-row-as-header.
    # One row per sheet row; values is an array of cell strings. When
    # use_first_row_as_header is true, the connector returns a dynamic
    # schema (row_index + named columns) instead.
    SHEET_VALUES_SCHEMA = StructType(
        [
            StructField("row_index", StringType(), nullable=True),
            StructField("values", ArrayType(StringType(), True), nullable=True),
        ]
    )

    # documents: Drive file list for mimeType=document; content is populated
    # when include_content is true (plain text via Drive export).
    DOCUMENTS_SCHEMA = StructType(
        [
            StructField("id", StringType(), nullable=False),
            StructField("name", StringType(), nullable=True),
            StructField("mimeType", StringType(), nullable=True),
            StructField("modifiedTime", StringType(), nullable=True),
            StructField("createdTime", StringType(), nullable=True),
            StructField("content", StringType(), nullable=True),
        ]
    )

    TABLE_SCHEMAS = {
        "spreadsheets": SPREADSHEETS_SCHEMA,
        "sheet_values": SHEET_VALUES_SCHEMA,
        "documents": DOCUMENTS_SCHEMA,
    }

    # ---------------------------------------------------------------------------
    # Table metadata for Lakeflow pipeline (primary keys, cursor, ingestion type)
    # ---------------------------------------------------------------------------
    # sheet_values primary_keys are set dynamically to [first_column] when
    # use_first_row_as_header is true and the first row can be fetched.
    TABLE_METADATA = {
        "spreadsheets": {
            "primary_keys": ["id"],
            "cursor_field": "modifiedTime",
            "ingestion_type": "snapshot",
        },
        "sheet_values": {
            "primary_keys": [],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        "documents": {
            "primary_keys": ["id"],
            "cursor_field": "modifiedTime",
            "ingestion_type": "snapshot",
        },
    }


    ########################################################
    # src/databricks/labs/community_connector/sources/google_sheets_docs/google_sheets_docs.py
    ########################################################

    TOKEN_URL = "https://oauth2.googleapis.com/token"
    DRIVE_FILES_URL = "https://www.googleapis.com/drive/v3/files"
    SHEETS_BASE_URL = "https://sheets.googleapis.com/v4/spreadsheets"
    DOCS_BASE_URL = "https://docs.googleapis.com/v1/documents"

    # Retry configuration for rate limits and server errors
    INITIAL_BACKOFF = 1.0
    MAX_RETRIES = 5
    RETRIABLE_STATUS_CODES = {429, 500, 503}


    class GoogleSheetsDocsLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for Google Sheets and Google Docs.

        Uses OAuth 2.0 refresh token flow to obtain access tokens for the Drive,
        Sheets, and Docs APIs. Options must include client_id, client_secret,
        and refresh_token.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """Initialize the connector with OAuth credentials.

            Args:
                options: Connection parameters. Must contain:
                    - client_id: OAuth 2.0 client ID from Google Cloud Console.
                    - client_secret: OAuth 2.0 client secret.
                    - refresh_token: Long-lived refresh token (access_type=offline).

            Raises:
                ValueError: If any of the three credentials are missing.
            """
            super().__init__(options)
            self._client_id = options.get("client_id")
            self._client_secret = options.get("client_secret")
            self._refresh_token = options.get("refresh_token")
            if not self._client_id or not self._client_secret or not self._refresh_token:
                raise ValueError(
                    "Google Sheets/Docs connector requires 'client_id', 'client_secret', "
                    "and 'refresh_token' in options"
                )
            # Cached access token; refreshed when near expiry
            self._access_token: str | None = None
            self._token_expires_at: float = 0
            self._session = requests.Session()

        def _get_access_token(self) -> str:
            """Exchange refresh_token for access_token; cache with 60s buffer.

            Returns a valid access token, refreshing from Google if cached token
            is missing or within 60 seconds of expiry.

            Returns:
                A valid Bearer access token for Google APIs.

            Raises:
                ValueError: If Google returns 401 (invalid/revoked credentials).
                requests.HTTPError: For other token endpoint errors.
            """
            # Use cached token if still valid with 60s safety margin
            if self._access_token and time.time() < self._token_expires_at - 60:
                return self._access_token
            resp = self._session.post(
                TOKEN_URL,
                data={
                    "client_id": self._client_id,
                    "client_secret": self._client_secret,
                    "refresh_token": self._refresh_token,
                    "grant_type": "refresh_token",
                },
                headers={"Content-Type": "application/x-www-form-urlencoded"},
            )
            # Provide clear guidance when credentials are rejected
            if resp.status_code == 401:
                try:
                    err = resp.json()
                    hint = err.get("error_description", err.get("error", resp.text))
                except Exception:
                    hint = resp.text or "Unauthorized"
                raise ValueError(
                    "Google OAuth returned 401 Unauthorized when refreshing the access token. "
                    "Check that the connection's client_id, client_secret, and refresh_token "
                    "are correct, that the refresh_token was obtained with the same OAuth "
                    "client (same client_id), and that it has not been revoked. Re-run the "
                    "OAuth flow if needed to get a new refresh_token. "
                    f"Google response: {hint}"
                ) from None
            resp.raise_for_status()
            try:
                data = resp.json()
            except ValueError as e:
                raise ValueError(
                    f"Google OAuth token endpoint returned invalid JSON: {e}"
                ) from e
            if "access_token" not in data:
                raise ValueError(
                    "Google OAuth token endpoint did not return an access_token. "
                    f"Response: {data}"
                )
            self._access_token = data["access_token"]
            self._token_expires_at = time.time() + data.get("expires_in", 3600)
            return self._access_token

        def _headers(self) -> dict[str, str]:
            """Return HTTP headers with a valid Bearer token for Google APIs."""
            return {
                "Authorization": f"Bearer {self._get_access_token()}",
                "Accept": "application/json",
            }

        def _request(
            self,
            method: str,
            url: str,
            *,
            params: dict[str, Any] | None = None,
            **kwargs: Any,
        ) -> requests.Response:
            """Issue HTTP request with exponential backoff on 429/5xx.

            Retries up to MAX_RETRIES times on rate limit (429) or server
            errors (500, 503). Other status codes are returned immediately.
            """
            backoff = INITIAL_BACKOFF
            for attempt in range(MAX_RETRIES):
                if "headers" not in kwargs:
                    kwargs["headers"] = self._headers()
                resp = self._session.request(method, url, params=params, **kwargs)
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp
                if attempt < MAX_RETRIES - 1:
                    time.sleep(backoff)
                    backoff *= 2
            return resp

        def _validate_table(self, table_name: str) -> None:
            """Raise ValueError if table_name is not one of the supported tables."""
            if table_name not in SUPPORTED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported: {SUPPORTED_TABLES}"
                )

        @staticmethod
        def _resolve_effective_table(table_name: str, table_options: dict[str, str]) -> str:
            """Resolve the connector table type when using an alias (e.g. source_table=stores).

            If table_configuration includes 'connector_table' or 'source_type' set to a
            supported type (sheet_values, spreadsheets, documents), use that for dispatch
            so the pipeline can use unique source_table names (stores, disasters) and
            avoid duplicate view names while still reading sheet_values.
            """
            effective = (
                table_options.get("connector_table")
                or table_options.get("source_type")
                or table_options.get("connectorTable")
                or table_options.get("sourceType")
            )
            if effective and str(effective).strip() in SUPPORTED_TABLES:
                return str(effective).strip()
            return table_name

        @staticmethod
        def _resolve_table_options(table_name: str, table_options: dict[str, str]) -> dict[str, str]:
            """Resolve per-table config when options are the full data source options.

            When the pipeline passes options that include 'tableConfigs' (JSON map of
            table name -> config), extract the config for this table so that
            spreadsheet_id, use_first_row_as_header, etc. are available. Otherwise
            return table_options as-is (caller already passed per-table config).
            """
            raw = table_options.get("tableConfigs")
            if not raw:
                return table_options
            try:
                table_configs = json.loads(raw)
            except (TypeError, ValueError):
                return table_options
            if not isinstance(table_configs, dict):
                return table_options
            # Values from spec are already string; ensure we have a dict of str -> str
            config = table_configs.get(table_name)
            if config is None:
                return table_options
            return {k: str(v) for k, v in config.items()} if isinstance(config, dict) else table_options

        def list_tables(self) -> list[str]:
            """Return the list of supported table names (spreadsheets, sheet_values, documents)."""
            return list(SUPPORTED_TABLES)

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """Return the Spark schema for the given table.

            For sheet_values with use_first_row_as_header and spreadsheet_id in
            table_options, fetches the first row and builds a dynamic schema
            (row_index + one column per header, Spark-safe names). Otherwise
            returns the static schema (e.g. row_index + values array).

            When table_configuration includes connector_table (or source_type) set to
            sheet_values, spreadsheets, or documents, that type is used so you can
            use unique source_table names (e.g. stores, disasters) in one pipeline.
            """
            opts = self._resolve_table_options(table_name, table_options)
            effective = self._resolve_effective_table(table_name, opts)
            self._validate_table(effective)
            if effective == "sheet_values" and self._sheet_values_use_headers(opts):
                schema = self._get_sheet_values_schema_with_headers(opts)
                if schema is not None:
                    return schema
            return TABLE_SCHEMAS[effective]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """Return table metadata (primary_keys, cursor_field, ingestion_type).

            For sheet_values with headers enabled, sets primary_keys to the
            first column name (e.g. ID) when the first row can be fetched.
            """
            opts = self._resolve_table_options(table_name, table_options)
            effective = self._resolve_effective_table(table_name, opts)
            self._validate_table(effective)
            meta = dict(TABLE_METADATA[effective])
            if effective == "sheet_values" and self._sheet_values_use_headers(opts):
                headers = self._fetch_sheet_first_row(opts)
                if headers:
                    meta["primary_keys"] = [headers[0]]
            return meta

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read records from the given table; returns (iterator, next_offset).

            Dispatches to the appropriate reader for spreadsheets, sheet_values,
            or documents. Offsets are used for Drive list pagination (pageToken).
            When connector_table (or source_type) is set in table_configuration,
            that type is used so unique source_table names can be used per sheet.
            """
            opts = self._resolve_table_options(table_name, table_options)
            effective = self._resolve_effective_table(table_name, opts)
            self._validate_table(effective)
            if effective == "spreadsheets":
                return self._read_spreadsheets(start_offset, opts)
            if effective == "sheet_values":
                return self._read_sheet_values(start_offset, opts)
            if effective == "documents":
                return self._read_documents(start_offset, opts)
            return iter([]), {}

        def _read_spreadsheets(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """List Drive files with mimeType=spreadsheet; paginate via pageToken.

            Uses Drive API files.list. start_offset may contain pageToken for
            the next page; when pageToken is explicitly None we signal end.
            """
            so = start_offset or {}
            # Sentinel: if caller passed pageToken: null, we're done paginating
            if so.get("pageToken") is None and "pageToken" in so:
                return iter([]), so
            page_token = so.get("pageToken") if so.get("pageToken") else None
            params: dict[str, Any] = {
                "q": "mimeType='application/vnd.google-apps.spreadsheet' and trashed=false",
                "pageSize": 100,
                "fields": "nextPageToken,files(id,name,mimeType,modifiedTime,createdTime)",
                "orderBy": "modifiedTime desc",
            }
            if page_token:
                params["pageToken"] = page_token

            resp = self._request("GET", DRIVE_FILES_URL, params=params)
            if resp.status_code == 403:
                raise ValueError(
                    "Drive API returned 403 Forbidden. Check that the refresh token has "
                    "https://www.googleapis.com/auth/drive.readonly scope and that the "
                    "Google Cloud project has the Drive API enabled."
                )
            resp.raise_for_status()
            try:
                data = resp.json()
            except ValueError as e:
                raise ValueError(
                    f"Drive API returned invalid JSON: {e}"
                ) from e
            files = data.get("files", [])
            next_token = data.get("nextPageToken")

            records = [
                {
                    "id": f.get("id"),
                    "name": f.get("name"),
                    "mimeType": f.get("mimeType"),
                    "modifiedTime": f.get("modifiedTime"),
                    "createdTime": f.get("createdTime"),
                }
                for f in files
            ]
            next_offset = {"pageToken": next_token} if next_token else {"pageToken": None}
            return iter(records), next_offset

        def _sheet_values_use_headers(self, table_options: dict[str, str]) -> bool:
            """Return True if sheet_values should treat the first row as column headers.

            Default is True unless use_first_row_as_header (or useFirstRowAsHeader) is
            'false', '0', or 'no'. Accepts both snake_case and camelCase for compatibility.
            """
            v = (
                table_options.get("use_first_row_as_header")
                or table_options.get("useFirstRowAsHeader")
                or "true"
            ).strip().lower()
            return v not in ("false", "0", "no")

        @staticmethod
        def _sanitize_column_name(raw: str, index: int) -> str:
            """Convert a sheet header to a Spark-safe column name.

            Produces only [a-zA-Z0-9_]; spaces and special chars become underscores.
            Empty or blank headers become _col{index}. Used to avoid "column not
            resolved" when Spark references columns without backticks.
            """
            s = (raw or "").strip()
            if not s:
                return f"_col{index}"
            # Replace non-alphanumeric (and non-underscore) with underscore, collapse underscores
            s = re.sub(r"[^a-zA-Z0-9_]+", "_", s)
            s = re.sub(r"_+", "_", s).strip("_")
            return s or f"_col{index}"

        def _fetch_sheet_first_row(self, table_options: dict[str, str]) -> list[str] | None:
            """Fetch the first row of the sheet and return Spark-safe column names.

            Calls Sheets API values.get for range {sheet_name}!1:1. Returns None
            only if spreadsheet_id is missing or first row is empty. Raises ValueError
            on API errors (404, 403) so callers see the real reason instead of
            silently falling back to row_index + values.
            """
            spreadsheet_id = table_options.get("spreadsheet_id") or table_options.get("spreadsheetId")
            if not spreadsheet_id:
                return None
            sheet_name = table_options.get("sheet_name", "Sheet1")
            range_a1 = f"{sheet_name}!1:1"
            url = f"{SHEETS_BASE_URL}/{spreadsheet_id}/values/{quote(range_a1, safe='')}"
            params = {"valueRenderOption": "UNFORMATTED_VALUE", "majorDimension": "ROWS"}
            resp = self._request("GET", url, params=params)
            if resp.status_code != 200:
                try:
                    err = resp.json()
                    msg = err.get("error", {}).get("message", resp.text)
                except (ValueError, TypeError):
                    msg = resp.text or f"HTTP {resp.status_code}"
                raise ValueError(
                    f"Sheets API returned {resp.status_code} for spreadsheet {spreadsheet_id!r} "
                    f"(range {range_a1}). Cannot use first row as headers. "
                    f"Check that the spreadsheet exists, is shared with the connection's account, "
                    f"and that sheet {sheet_name!r} exists. Details: {msg}"
                )
            try:
                data = resp.json()
            except ValueError:
                return None
            values = data.get("values", [])
            if not values:
                return None
            return [
                self._sanitize_column_name(str(h), i) for i, h in enumerate(values[0])
            ]

        def _get_sheet_values_schema_with_headers(
            self, table_options: dict[str, str]
        ) -> StructType | None:
            """Build a StructType with row_index plus one string column per header.

            Used when use_first_row_as_header is true so that get_table_schema
            returns a schema matching the named columns we emit in read_table.
            Returns None if the first row cannot be fetched (no spreadsheet_id or API error).
            """
            headers = self._fetch_sheet_first_row(table_options)
            if not headers:
                return None
            fields = [StructField("row_index", StringType(), nullable=True)]
            for col in headers:
                fields.append(StructField(col, StringType(), nullable=True))
            return StructType(fields)

        def _read_sheet_values(  # pylint: disable=too-many-locals
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read cell data via Sheets API values.get.

            Requires spreadsheet_id (or spreadsheetId) in table_options. Optional:
            sheet_name (default Sheet1), range (default A:Z), use_first_row_as_header
            (default true). When use_first_row_as_header is true, first row becomes
            column names and data rows are emitted as named columns (Spark-safe);
            otherwise each row is row_index + values array.
            """
            spreadsheet_id = table_options.get("spreadsheet_id") or table_options.get(
                "spreadsheetId"
            )
            if not spreadsheet_id:
                raise ValueError(
                    "table_options must include 'spreadsheet_id' or 'spreadsheetId' for sheet_values"
                )
            sheet_name = table_options.get("sheet_name", "Sheet1")
            range_a1 = table_options.get("range", "A:Z")
            if "!" not in range_a1:
                range_a1 = f"{sheet_name}!{range_a1}"

            url = f"{SHEETS_BASE_URL}/{spreadsheet_id}/values/{quote(range_a1, safe='')}"
            params = {"valueRenderOption": "UNFORMATTED_VALUE", "majorDimension": "ROWS"}
            resp = self._request("GET", url, params=params)
            if resp.status_code == 404:
                return iter([]), {}
            if resp.status_code == 403:
                raise ValueError(
                    "Sheets API returned 403 Forbidden. Check that the refresh token has "
                    "https://www.googleapis.com/auth/spreadsheets.readonly scope and that "
                    "the Google Cloud project has the Sheets API enabled."
                )
            # 400 often means ID is an .xlsx file; Sheets API only supports native spreadsheets
            if resp.status_code == 400:
                try:
                    err_body = resp.json()
                    err_msg = err_body.get("error", {}).get("message", resp.text)
                except ValueError:
                    err_msg = resp.text or "Bad Request"
                raise ValueError(
                    f"Sheets API rejected the request (400). The spreadsheet ID may point "
                    f"to an Excel (.xlsx) file instead of a native Google Sheet. In Drive, "
                    f"open the file with Google Sheets, then File → Save as Google Sheets "
                    f"and use the new file's ID. API error: {err_msg}"
                )
            resp.raise_for_status()
            try:
                data = resp.json()
            except ValueError as e:
                raise ValueError(
                    f"Sheets API returned invalid JSON: {e}"
                ) from e
            values = data.get("values", [])

            use_headers = self._sheet_values_use_headers(table_options)
            if use_headers and len(values) >= 1:
                # First row = headers (sanitized); remaining rows = data with named columns
                headers = [
                    self._sanitize_column_name(str(h), i) for i, h in enumerate(values[0])
                ]
                records = []
                for i, row in enumerate(values[1:], start=2):
                    str_row = [str(c) if c is not None else "" for c in row]
                    rec = {"row_index": str(i)}
                    for j, col in enumerate(headers):
                        rec[col] = str_row[j] if j < len(str_row) else ""
                    records.append(rec)
                return iter(records), {}
            # Raw mode: every row is row_index + values array
            records = [
                {"row_index": str(i + 1), "values": [str(c) if c is not None else "" for c in row]}
                for i, row in enumerate(values)
            ]
            return iter(records), {}

        def _read_documents(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """List Drive files with mimeType=document; optionally fetch body content.

            Paginates via pageToken. When include_content is true/1/yes, each
            file's plain-text content is fetched via Drive files.export.
            """
            so = start_offset or {}
            if so.get("pageToken") is None and "pageToken" in so:
                return iter([]), so
            page_token = so.get("pageToken") if so.get("pageToken") else None
            params: dict[str, Any] = {
                "q": "mimeType='application/vnd.google-apps.document' and trashed=false",
                "pageSize": 100,
                "fields": "nextPageToken,files(id,name,mimeType,modifiedTime,createdTime)",
                "orderBy": "modifiedTime desc",
            }
            if page_token:
                params["pageToken"] = page_token

            resp = self._request("GET", DRIVE_FILES_URL, params=params)
            if resp.status_code == 403:
                raise ValueError(
                    "Drive API returned 403 Forbidden. Check that the refresh token has "
                    "https://www.googleapis.com/auth/drive.readonly scope and that the "
                    "Google Cloud project has the Drive API enabled."
                )
            resp.raise_for_status()
            try:
                data = resp.json()
            except ValueError as e:
                raise ValueError(
                    f"Drive API returned invalid JSON: {e}"
                ) from e
            files = data.get("files", [])
            next_token = data.get("nextPageToken")

            include_content = table_options.get("include_content", "").lower() in (
                "true",
                "1",
                "yes",
            )

            records = []
            for f in files:
                doc_id = f.get("id")
                rec = {
                    "id": doc_id,
                    "name": f.get("name"),
                    "mimeType": f.get("mimeType"),
                    "modifiedTime": f.get("modifiedTime"),
                    "createdTime": f.get("createdTime"),
                    "content": None,
                }
                if include_content and doc_id:
                    rec["content"] = self._fetch_document_content(doc_id)
                records.append(rec)

            next_offset = {"pageToken": next_token} if next_token else {"pageToken": None}
            return iter(records), next_offset

        def _fetch_document_content(self, document_id: str) -> str | None:
            """Fetch document body as plain text via Drive files.export.

            Uses mimeType=text/plain. Returns None on failure (e.g. 403, 404,
            or non-200). Subject to Drive export size limits (e.g. 10 MB).
            Does not raise; failures are treated as missing content.
            """
            url = f"https://www.googleapis.com/drive/v3/files/{document_id}/export"
            try:
                resp = self._request(
                    "GET", url, params={"mimeType": "text/plain"}
                )
            except Exception:
                return None
            if resp.status_code != 200:
                return None
            return resp.text if resp.text else None


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = GoogleSheetsDocsLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name != METADATA_TABLE:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
